SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [preods].[SurveyGizmo_surveyResponse]
AS

SELECT DISTINCT
	[ETL__multi_query_value_for_audit]
	,CONVERT(INT,[SK]) [SK_K]
	,CONVERT(INT,[Response_id]) [Response_id_K]
	,CONVERT(NVARCHAR(256),[Response_contact-id]) [Response_contact_id]
	,CONVERT(NVARCHAR(50),[Response_status]) [Response_status]
	,CONVERT(BIT,[Response_is-test-data]) [Response_is_test_data]
	,CONVERT(NVARCHAR(20),[Response_date-submitted]) [Response_date_submitted]
	,CONVERT(NVARCHAR(500),[Response_session-id]) [Response_session_id]
	,CONVERT(NVARCHAR(50),[Response_language]) [Response_language]
	,CONVERT(NVARCHAR(20),[Response_date-started]) [Response_date_started]
	,CONVERT(INT,[Response_link-id]) [Response_link_id]
	,CONVERT(NVARCHAR(20),[Response_ip-address]) [Response_ip_address]
	,CONVERT(NVARCHAR(MAX),[Response_referer]) [Response_referer]
	,CONVERT(NVARCHAR(MAX),[Response_user-agent]) [Response_user_agent]
	,CONVERT(INT,[Response_response-time]) [Response_response_time]
	,CONVERT(DECIMAL(20,17),[Response_longitude]) [Response_longitude]
	,CONVERT(DECIMAL(20,17),[Response_latitude]) [Response_latitude]
	,CONVERT(NVARCHAR(50),[Response_country]) [Response_country]
	,CONVERT(NVARCHAR(50),[Response_city]) [Response_city]
	,CONVERT(NVARCHAR(50),[Response_region]) [Response_region]
	,CONVERT(NVARCHAR(20),[Response_postal]) [Response_postal]
	,CONVERT(INT, [Response_dma]) [Response_dma]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_controller]) [Response_url_variables_controller]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_controller_key]) [Response_url_variables_controller_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_controller_value]) [Response_url_variables_controller_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_controller_type]) [Response_url_variables_controller_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_action_key]) [Response_url_variables_action_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_action_value]) [Response_url_variables_action_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_action_type]) [Response_url_variables_action_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_id_key]) [Response_url_variables_id_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_id_value]) [Response_url_variables_id_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_id_type]) [Response_url_variables_id_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_module_key]) [Response_url_variables_module_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_module_value]) [Response_url_variables_module_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_module_type]) [Response_url_variables_module_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sgtarget_key]) [Response_url_variables___sgtarget_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sgtarget_value]) [Response_url_variables___sgtarget_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sgtarget_type]) [Response_url_variables___sgtarget_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_slanguage_key]) [Response_url_variables_slanguage_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_slanguage_value]) [Response_url_variables_slanguage_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_slanguage_type]) [Response_url_variables_slanguage_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-build-test_key]) [Response_url_variables___sg_build_test_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-build-test_value]) [Response_url_variables___sg_build_test_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-build-test_type]) [Response_url_variables___sg_build_test_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-collab-test_key]) [Response_url_variables___sg_collab_test_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-collab-test_value]) [Response_url_variables___sg_collab_test_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-collab-test_type]) [Response_url_variables___sg_collab_test_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-tester_key]) [Response_url_variables___sg_tester_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-tester_value]) [Response_url_variables___sg_tester_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-tester_type]) [Response_url_variables___sg_tester_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-tester-name_key]) [Response_url_variables___sg_tester_name_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-tester-name_value]) [Response_url_variables___sg_tester_name_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-tester-name_type]) [Response_url_variables___sg_tester_name_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-tester-id_key]) [Response_url_variables___sg_tester_id_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-tester-id_value]) [Response_url_variables___sg_tester_id_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-tester-id_type]) [Response_url_variables___sg_tester_id_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_link-id_key]) [Response_url_variables_link_id_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_link-id_value]) [Response_url_variables_link_id_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_link-id_type]) [Response_url_variables_link_id_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-skip-actions_key]) [Response_url_variables___sg_skip_actions_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-skip-actions_value]) [Response_url_variables___sg_skip_actions_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sg-skip-actions_type]) [Response_url_variables___sg_skip_actions_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_?preview-frame_key]) [Response_url_variables_?preview_frame_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_?preview-frame_value]) [Response_url_variables_?preview_frame_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_?preview-frame_type]) [Response_url_variables_?preview_frame_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sgapptest_key]) [Response_url_variables___sgapptest_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sgapptest_value]) [Response_url_variables___sgapptest_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--sgapptest_type]) [Response_url_variables___sgapptest_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--ref_key]) [Response_url_variables___ref_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--ref_value]) [Response_url_variables___ref_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--ref_type]) [Response_url_variables___ref_type]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--passthrough_key]) [Response_url_variables___passthrough_key]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--passthrough_value]) [Response_url_variables___passthrough_value]
	,CONVERT(NVARCHAR(MAX),[Response_url-variables_--passthrough_type]) [Response_url_variables___passthrough_type]
	,CONVERT(INT,[Response_survey-data_id]) [Response_survey_data_id]
	,CONVERT(NVARCHAR(20),[Response_survey-data_type]) [Response_survey_data_type]
	,CONVERT(NVARCHAR(500),[Response_survey-data_question]) [Response_survey_data_question]
	,CONVERT(INT,[Response_survey-data_section-id]) [Response_survey_data_section_id]
	,CONVERT(NVARCHAR(20),[Response_survey-data_shown]) [Response_survey_data_shown]
	,CONVERT(NVARCHAR(MAX),[Response_survey-data_options_]) [Response_survey_data_options_]
	,CONVERT(INT,[Response_survey-data_options_id]) [Response_survey_data_options_id]
	,CONVERT(NVARCHAR(100),[Response_survey-data_options_option]) [Response_survey_data_options_option]
	,CONVERT(NVARCHAR(MAX),[Response_survey-data_options_answer]) [Response_survey_data_options_answer]
	,CONVERT(NVARCHAR(20),[Response_survey-data_options_card_id]) [Response_survey_data_options_card_id]
	,CONVERT(NVARCHAR(MAX),[Response_survey-data_options_card_answer]) [Response_survey_data_options_card_answer]
	,CONVERT(NVARCHAR(20),[Response_survey-data_options_set_id]) [Response_survey_data_options_set_id]
	,CONVERT(NVARCHAR(MAX),[Response_survey-data_options_set_answer]) [Response_survey_data_options_set_answer]
	,CONVERT(NVARCHAR(20),[Response_survey-data_options_choice_id]) [Response_survey_data_options_choice_id]
	,CONVERT(NVARCHAR(MAX),[Response_survey-data_options_choice_answer]) [Response_survey_data_options_choice_answer]
FROM [src].[SurveyGizmo_surveyResponse] WITH (NOLOCK)
GO
