SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO





CREATE PROCEDURE [etl].[Load_ods_Eloqua_Contact]
(
	@BatchId INT = 0,
	@Options NVARCHAR(MAX) = null
)
AS 

BEGIN
/**************************************Comments***************************************
**************************************************************************************
Mod #:  1
Name:     dbo
Date:     05/04/2017
Comments: Initial creation
*************************************************************************************/

DECLARE @RunTime DATETIME = GETDATE();

DECLARE @ExecutionId uniqueidentifier = newid();
DECLARE @ProcedureName nvarchar(255) = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID);
DECLARE @SrcRowCount int = ISNULL((SELECT CONVERT(varchar, COUNT(*)) FROM stg.Eloqua_Contact),'0');	
DECLARE @SrcDataSize NVARCHAR(255) = '0';

/*Load Options into a temp table*/
SELECT Col1 AS OptionKey, Col2 as OptionValue INTO #Options FROM [dbo].[SplitMultiColumn](@Options, '=', ';');

/*Extract Options, default values set if the option is not specified*/	
DECLARE @DisableInsert nvarchar(5) = ISNULL((SELECT OptionValue FROM #Options WHERE OptionKey = 'DisableInsert'),'false');
DECLARE @DisableUpdate nvarchar(5) = ISNULL((SELECT OptionValue FROM #Options WHERE OptionKey = 'DisableUpdate'),'false');
DECLARE @DisableDelete nvarchar(5) = ISNULL((SELECT OptionValue FROM #Options WHERE OptionKey = 'DisableDelete'),'true');


BEGIN TRY 


SELECT CAST(NULL AS BINARY(32)) ETL_DeltaHashKey
,  ID, Name, AccountName, BouncebackDate, IsBounceback, IsSubscribed, PostalCode, Province, SubscriptionDate, UnsubscriptionDate, CreatedAt, CreatedBy, AccessedAt, CurrentStatus, Depth, UpdatedAt, UpdatedBy, EmailAddress, FirstName, LastName, Company, Address1, Address2, Address3, City, Country, MobilePhone, BusinessPhone, Fax, Title, SalesPerson, C_State_Prov, C_Zip_Postal, C_Salutation, C_Account, C_SFDCContactID, C_SFDCLeadID, C_Website, C_DateCreated, C_DateModified, ContactIDExt, C_SFDCAccountID, C_LastModifiedByExtIntegrateSystem, C_SFDCLastCampaignID, C_SFDCLastCampaignStatus, C_Last_Lead_Rating1, C_Last_Lead_Score1, C_Lead_Score___Historical_All_Time1, C_Lead_Rating___Historical_All_Time__HAT_1, C_Company_Revenue1, C_SFDC_EmailOptOut1, C_Lead_Source___Most_Recent1, C_Lead_Source___Original1, C_Industry1, C_Lead_Status1, C_Job_Role1, C_Last_Website_Visit_Date_and_Time1, C_LS___High_Value_Website_Content1, C_DUNS_Number, C_Doing_Business_As, C_CEO_Name, C_Industry, C_SIC_Code, C_Established_In, C_Annual_Sales_Indicator, C_Annual_Sales, C_Total_Employees, C_Total_Employees_Indicator, C_Lead_Score_Date___Most_Recent1, C_Integrated_Marketing_and_Sales_Funnel_Stage, C_Product_Solution_of_Interest1, C_Region1, C_elqPURLName1, C_Most_Recent_Form_Submitted1, C_Household_Income1, C___of_Times_Downloaded_High_Valued_Content__, C___of_Times_Downloaded_High_Valued_Content__3, C___of_Times_Downloaded_High_Valued_Content__4, C_Lead_Rating___Combined1, C_Purchase_History___Most_Recent1, C___Times_Viewed_High_Value_Content___ALL1, C_Total_Visits1, C_Daytime_Phone1, C_Evening_Phone1, C_Name_Last1, C_Acct_Type_Desc1, C_Email_Opt_In1, C_Birthdate1, C_Favorite_Player1, C_elqPURLName3, C_EmailAddressDomain, C_FirstAndLastName, C_Best_Time_to_Conact1, C_Mobile_Opt_In1, C_Guest_Services_Rep1, C_Phone1, C_Season1, C_Gender1, C_Renewal_Memo_Code1, C_Payment_Memo_Code1, C_Number_of_Seats1, C_Select_a_seat_2011_12_Yes_No1, C_2011_12_Sales_Pack_Interest1, C_Contact_Preference_for_Sales1, C_Executive_Suite_Interest1, C_Group_Size_Interest1, C_Attention_Name1, C_Alt_Address_11, C_Alt_Address_21, C_Alt_City1, C_Alt_Zip_Code1, C_Alt_State1, C_Alt_Company1, C_SFDCLastCampaignName, C_SFDC_Lead_Rating1, C_Caps_STH_Loyalty1, C_Guest_Services_Reps_II1, C_elqPURLName4, C_elqPURLName5, C_elqPURLName6, C_SFDC_Interests1, C_Suite_Facility1, C_Suite__1, C_Suite_Seats1, C_Lead_Score___Last_High_Touch_Event_Date1, C_Last_Single_Game_Ticket_Purchase_Date1, C_B2C___Lead_Rating___Combined1, C_B2C___Lead_Rating___Explicit1, C_B2C___Lead_Score___Explicit1, C_B2C___Lead_Rating___Implicit1, C_B2C___Lead_Score___High_Value_Website_Conte, C_B2C___Lead_Score___Implicit1, C_B2C___Lead_Score_Date___Most_Recent1, C_Number_of_Employees1, C_Past_Purchases__Suite___Sponsorships_1, C_Zip_Code__Georgraphic_Area_1, C_Previous_Purchase1, C_Discretionary_Income1, C_Wizards_Account_ID1, C_Mystics_Account_ID1, C_Interests1, C_Annual_Revenue1, C_Turnkey_Rating___Score1, C_Child_11, C_Child_21, C_Child_31, C_Season_Ticket_Holder1, C_Wiz___Balance_Due1, C_Wiz___Guest_Services_Reps1, C_Child_41, C_Child_51, C_Child_2_Birthday1, C_Child_1_Birthday1, C_Caps_Kids_Club1, C_Caps_Kids_Club_Referral_Email1, C_Birthdate_C1, C_Birthdate_W1, C_Birthdate_M1, C_Type_of_Mobile_Phone1, C_Caps___12_13_Par__STH__Dep__Premium_Renewal, C_Rep_Phone1, C_Rep_Email1, C_Package_Interest1, C_Question_Comments1, C_Premium_Package_Rep1, C_Caps_Non_Renewed_Rep1, C_Referred_by_First_Name1, C_Referred_by_Last_Name1, C_Territory, C_SFDC_Ticket___Rep_Name1, C_SFDC_Ticket___Price_Code1, C_SFDC_Ticket___Event_Name1, C_SFDC_Ticket___Purchase_Qty1, C_SFDC_Ticket___Purchase_Price1, C_SFDC_Ticket___Archtics_ID1, C_SFDC_Ticket___Purchase_Date1, C_SFDC_Ticket___First_Name1, C_Caps___Holiday_PURL1, C_Wiz___Holiday_E_Card_Purl1, C_Wiz___Holiday_Pack_Game_11, C_Wiz___Holiday_Pack_Game_21, C_Lead_Score, C_ElqPURLName, C_Suites___Rep_Name1, C_Caps___STH_Presale_Time1, C_Caps_TA_and_IC_Opt_Ins1, C_Twitter_Handle1, C_Sales_Rep_First_Name1, C_Full_Name1, C_MSE_Account_ID1, C_Last_4_CC_Digits1, C_CC_Type1, C_CC_Expiration1, C_Rep_Title1, C_Decline_Amount_Due1, C_Wiz___Canopy_Data1, C_MSE_Rewards_Amount1, C_Wiz___PG_Season_Name1, C_Wiz___PG_Event_Opponent1, C_Wiz___PG_Event_Date1, C_MSE___Current_Rewards_Points1, C_MSE___Accrued_Rewards_Points1, C_MSE_____of_Rewards_Logins1, C_MSE___Last_Rewards_Login1, C_MSE___Spent_Rewards_Points1, C_Wiz___STH_Presale_Timeslot1, C_MD5HashedEmailAddress, C_SHA256HashedEmailAddress, C_MD5HashedBusPhone, C_SHA256HashedBusPhone, C_MD5HashedMobilePhone, C_SHA256HashedMobilePhone, C_Wiz___Promo_Code1, C_Caps_201516_Renewal_PURL1, C_Caps___Kids_Club_Expire_Date1, C_Caps___SAS_Timeslot1, C_STH_Since_Date__Caps1, C_Caps_Sales_Rep_Full_Name1, C_Caps_Sales_Rep_First_Name1, C_Caps_Sales_Rep_Last_Name1, C_Caps_Sales_Rep_Email1, C_Caps_Sales_Rep_Phone1, C_Caps_Sales_Rep_Title1, C_Wiz_Sales_Rep_Full_Name1, C_Wiz_Sales_Rep_First_Name1, C_Wiz_Sales_Rep_Last_Name1, C_Wiz_Sales_Rep_Email1, C_Wiz_Sales_Rep_Phone1, C_Wiz_Sales_Rep_Title1, C_Mys_Sales_Rep_Full_Name1, C_Mys_Sales_Rep_First_Name1, C_Mys_Sales_Rep_Last_Name1, C_Mys_Sales_Rep_Email1, C_Mys_Sales_Rep_Phone1, C_Mys_Sales_Rep_Title1, C_MSE_Sales_Rep_Full_Name1, C_MSE_Sales_Rep_First_Name1, C_MSE_Sales_Rep_Last_Name1, C_MSE_Sales_Rep_Email1, C_MSE_Sales_Rep_Phone1, C_MSE_Sales_Rep_Title1, C_Alt_Country1, C_Caps_RepTM_Link_11, C_Wiz_RepTM_Link_11, C_Mys_RepTM_Link_11, C_Caps_PURL_11, C_Wiz_PURL_11, C_Mys_PURL_11, C_Mys_STH_Presale_Timeslot1, C_MSE_STH_Presale_Timeslot1, C_Caps_Promo_Code_11, C_Mys_Promo_Code_11, C_Caps_Canopy_Data1, C_Mys_Canopy_Data1, C_MSE_Canopy_Data1, C_Caps_Balance_Due1, C_Caps_Decline_Amount_Due1, C_Wiz_Decline_Amount_Due1, C_Mys_Balance_Due1, C_Mys_Decline_Amount_Due1, C_MSE_Balance_Due1, C_MSE_Decline_Amount_Due1, C_Caps_Number_of_Group_Seats1, C_Wiz_Number_of_Group_Seats1, C_Mys_Number_of_Group_Seats1, C_MSE_Number_of_Group_Seats1, C_Caps_Number_of_Group_Games1, C_Wiz_Number_of_Group_Games1, C_Mys_Number_of_Group_Games1, C_MSE_Number_of_Group_Games1, C_Caps_Focus_Group_Time1, C_Wiz_Focus_Group_Time1, C_Section1, C_Row1, C_Caps___Number_Attending1, C_Child_3_Birthday1, C_Child_4_Birthday1, C_Child_5_Birthday1, C_Caps_GS_Rep_Email1, C_Caps_GS_Rep_First_Name1, C_Caps_GS_Rep_Last_Name1, C_Caps_GS_Rep_Full_Name1, C_Caps_GS_Rep_Phone1, C_Caps_GS_Rep_Title1, C_Wiz_GS_Rep_Email1, C_Wiz_GS_Rep_First_Name1, C_Wiz_GS_Rep_Last_Name1, C_Wiz_GS_Rep_Full_Name1, C_Wiz_GS_Rep_Phone1, C_Wiz_GS_Rep_Title1, C_Mys_GS_Rep_Email1, C_Mys_GS_Rep_First_Name1, C_Mys_GS_Rep_Last_name1, C_Mys_GS_Rep_Full_Name1, C_Mys_GS_Rep_Phone1, C_Mys_GS_Rep_Title1, C_MSE_Rewards_Type1, C_Wiz_Loyalty_Level1, C_Package_Tracking_Number1, C_MSE_RepTM_Link_11, C_Gift_Tracking__11, C_MSE_Focus_Group_Time1, C_AB_Randomized1, C_Automation_Yes1_No01, C_LinkedIn_Profile1, C_Facebook_Profile1, C_Ticket_Type1, C_MSE_Renewal_Status1, C_AFL___Sales_Rep_Full_Name1, C_AFL___Sales_Rep_Email1, C_AFL___Sales_Rep_First_Name1, C_AFL___Sales_Rep_Last_Name1, C_AFL___Sales_Rep_Phone1, C_AFL___Sales_Rep_Title1, C_Seat_Number1, C_MSE_Team1
INTO #SrcData
FROM (
	SELECT  ID, Name, AccountName, BouncebackDate, IsBounceback, IsSubscribed, PostalCode, Province, SubscriptionDate, UnsubscriptionDate, CreatedAt, CreatedBy, AccessedAt, CurrentStatus, Depth, UpdatedAt, UpdatedBy, EmailAddress, FirstName, LastName, Company, Address1, Address2, Address3, City, Country, MobilePhone, BusinessPhone, Fax, Title, SalesPerson, C_State_Prov, C_Zip_Postal, C_Salutation, C_Account, C_SFDCContactID, C_SFDCLeadID, C_Website, C_DateCreated, C_DateModified, ContactIDExt, C_SFDCAccountID, C_LastModifiedByExtIntegrateSystem, C_SFDCLastCampaignID, C_SFDCLastCampaignStatus, C_Last_Lead_Rating1, C_Last_Lead_Score1, C_Lead_Score___Historical_All_Time1, C_Lead_Rating___Historical_All_Time__HAT_1, C_Company_Revenue1, C_SFDC_EmailOptOut1, C_Lead_Source___Most_Recent1, C_Lead_Source___Original1, C_Industry1, C_Lead_Status1, C_Job_Role1, C_Last_Website_Visit_Date_and_Time1, C_LS___High_Value_Website_Content1, C_DUNS_Number, C_Doing_Business_As, C_CEO_Name, C_Industry, C_SIC_Code, C_Established_In, C_Annual_Sales_Indicator, C_Annual_Sales, C_Total_Employees, C_Total_Employees_Indicator, C_Lead_Score_Date___Most_Recent1, C_Integrated_Marketing_and_Sales_Funnel_Stage, C_Product_Solution_of_Interest1, C_Region1, C_elqPURLName1, C_Most_Recent_Form_Submitted1, C_Household_Income1, C___of_Times_Downloaded_High_Valued_Content__, C___of_Times_Downloaded_High_Valued_Content__3, C___of_Times_Downloaded_High_Valued_Content__4, C_Lead_Rating___Combined1, C_Purchase_History___Most_Recent1, C___Times_Viewed_High_Value_Content___ALL1, C_Total_Visits1, C_Daytime_Phone1, C_Evening_Phone1, C_Name_Last1, C_Acct_Type_Desc1, C_Email_Opt_In1, C_Birthdate1, C_Favorite_Player1, C_elqPURLName3, C_EmailAddressDomain, C_FirstAndLastName, C_Best_Time_to_Conact1, C_Mobile_Opt_In1, C_Guest_Services_Rep1, C_Phone1, C_Season1, C_Gender1, C_Renewal_Memo_Code1, C_Payment_Memo_Code1, C_Number_of_Seats1, C_Select_a_seat_2011_12_Yes_No1, C_2011_12_Sales_Pack_Interest1, C_Contact_Preference_for_Sales1, C_Executive_Suite_Interest1, C_Group_Size_Interest1, C_Attention_Name1, C_Alt_Address_11, C_Alt_Address_21, C_Alt_City1, C_Alt_Zip_Code1, C_Alt_State1, C_Alt_Company1, C_SFDCLastCampaignName, C_SFDC_Lead_Rating1, C_Caps_STH_Loyalty1, C_Guest_Services_Reps_II1, C_elqPURLName4, C_elqPURLName5, C_elqPURLName6, C_SFDC_Interests1, C_Suite_Facility1, C_Suite__1, C_Suite_Seats1, C_Lead_Score___Last_High_Touch_Event_Date1, C_Last_Single_Game_Ticket_Purchase_Date1, C_B2C___Lead_Rating___Combined1, C_B2C___Lead_Rating___Explicit1, C_B2C___Lead_Score___Explicit1, C_B2C___Lead_Rating___Implicit1, C_B2C___Lead_Score___High_Value_Website_Conte, C_B2C___Lead_Score___Implicit1, C_B2C___Lead_Score_Date___Most_Recent1, C_Number_of_Employees1, C_Past_Purchases__Suite___Sponsorships_1, C_Zip_Code__Georgraphic_Area_1, C_Previous_Purchase1, C_Discretionary_Income1, C_Wizards_Account_ID1, C_Mystics_Account_ID1, C_Interests1, C_Annual_Revenue1, C_Turnkey_Rating___Score1, C_Child_11, C_Child_21, C_Child_31, C_Season_Ticket_Holder1, C_Wiz___Balance_Due1, C_Wiz___Guest_Services_Reps1, C_Child_41, C_Child_51, C_Child_2_Birthday1, C_Child_1_Birthday1, C_Caps_Kids_Club1, C_Caps_Kids_Club_Referral_Email1, C_Birthdate_C1, C_Birthdate_W1, C_Birthdate_M1, C_Type_of_Mobile_Phone1, C_Caps___12_13_Par__STH__Dep__Premium_Renewal, C_Rep_Phone1, C_Rep_Email1, C_Package_Interest1, C_Question_Comments1, C_Premium_Package_Rep1, C_Caps_Non_Renewed_Rep1, C_Referred_by_First_Name1, C_Referred_by_Last_Name1, C_Territory, C_SFDC_Ticket___Rep_Name1, C_SFDC_Ticket___Price_Code1, C_SFDC_Ticket___Event_Name1, C_SFDC_Ticket___Purchase_Qty1, C_SFDC_Ticket___Purchase_Price1, C_SFDC_Ticket___Archtics_ID1, C_SFDC_Ticket___Purchase_Date1, C_SFDC_Ticket___First_Name1, C_Caps___Holiday_PURL1, C_Wiz___Holiday_E_Card_Purl1, C_Wiz___Holiday_Pack_Game_11, C_Wiz___Holiday_Pack_Game_21, C_Lead_Score, C_ElqPURLName, C_Suites___Rep_Name1, C_Caps___STH_Presale_Time1, C_Caps_TA_and_IC_Opt_Ins1, C_Twitter_Handle1, C_Sales_Rep_First_Name1, C_Full_Name1, C_MSE_Account_ID1, C_Last_4_CC_Digits1, C_CC_Type1, C_CC_Expiration1, C_Rep_Title1, C_Decline_Amount_Due1, C_Wiz___Canopy_Data1, C_MSE_Rewards_Amount1, C_Wiz___PG_Season_Name1, C_Wiz___PG_Event_Opponent1, C_Wiz___PG_Event_Date1, C_MSE___Current_Rewards_Points1, C_MSE___Accrued_Rewards_Points1, C_MSE_____of_Rewards_Logins1, C_MSE___Last_Rewards_Login1, C_MSE___Spent_Rewards_Points1, C_Wiz___STH_Presale_Timeslot1, C_MD5HashedEmailAddress, C_SHA256HashedEmailAddress, C_MD5HashedBusPhone, C_SHA256HashedBusPhone, C_MD5HashedMobilePhone, C_SHA256HashedMobilePhone, C_Wiz___Promo_Code1, C_Caps_201516_Renewal_PURL1, C_Caps___Kids_Club_Expire_Date1, C_Caps___SAS_Timeslot1, C_STH_Since_Date__Caps1, C_Caps_Sales_Rep_Full_Name1, C_Caps_Sales_Rep_First_Name1, C_Caps_Sales_Rep_Last_Name1, C_Caps_Sales_Rep_Email1, C_Caps_Sales_Rep_Phone1, C_Caps_Sales_Rep_Title1, C_Wiz_Sales_Rep_Full_Name1, C_Wiz_Sales_Rep_First_Name1, C_Wiz_Sales_Rep_Last_Name1, C_Wiz_Sales_Rep_Email1, C_Wiz_Sales_Rep_Phone1, C_Wiz_Sales_Rep_Title1, C_Mys_Sales_Rep_Full_Name1, C_Mys_Sales_Rep_First_Name1, C_Mys_Sales_Rep_Last_Name1, C_Mys_Sales_Rep_Email1, C_Mys_Sales_Rep_Phone1, C_Mys_Sales_Rep_Title1, C_MSE_Sales_Rep_Full_Name1, C_MSE_Sales_Rep_First_Name1, C_MSE_Sales_Rep_Last_Name1, C_MSE_Sales_Rep_Email1, C_MSE_Sales_Rep_Phone1, C_MSE_Sales_Rep_Title1, C_Alt_Country1, C_Caps_RepTM_Link_11, C_Wiz_RepTM_Link_11, C_Mys_RepTM_Link_11, C_Caps_PURL_11, C_Wiz_PURL_11, C_Mys_PURL_11, C_Mys_STH_Presale_Timeslot1, C_MSE_STH_Presale_Timeslot1, C_Caps_Promo_Code_11, C_Mys_Promo_Code_11, C_Caps_Canopy_Data1, C_Mys_Canopy_Data1, C_MSE_Canopy_Data1, C_Caps_Balance_Due1, C_Caps_Decline_Amount_Due1, C_Wiz_Decline_Amount_Due1, C_Mys_Balance_Due1, C_Mys_Decline_Amount_Due1, C_MSE_Balance_Due1, C_MSE_Decline_Amount_Due1, C_Caps_Number_of_Group_Seats1, C_Wiz_Number_of_Group_Seats1, C_Mys_Number_of_Group_Seats1, C_MSE_Number_of_Group_Seats1, C_Caps_Number_of_Group_Games1, C_Wiz_Number_of_Group_Games1, C_Mys_Number_of_Group_Games1, C_MSE_Number_of_Group_Games1, C_Caps_Focus_Group_Time1, C_Wiz_Focus_Group_Time1, C_Section1, C_Row1, C_Caps___Number_Attending1, C_Child_3_Birthday1, C_Child_4_Birthday1, C_Child_5_Birthday1, C_Caps_GS_Rep_Email1, C_Caps_GS_Rep_First_Name1, C_Caps_GS_Rep_Last_Name1, C_Caps_GS_Rep_Full_Name1, C_Caps_GS_Rep_Phone1, C_Caps_GS_Rep_Title1, C_Wiz_GS_Rep_Email1, C_Wiz_GS_Rep_First_Name1, C_Wiz_GS_Rep_Last_Name1, C_Wiz_GS_Rep_Full_Name1, C_Wiz_GS_Rep_Phone1, C_Wiz_GS_Rep_Title1, C_Mys_GS_Rep_Email1, C_Mys_GS_Rep_First_Name1, C_Mys_GS_Rep_Last_name1, C_Mys_GS_Rep_Full_Name1, C_Mys_GS_Rep_Phone1, C_Mys_GS_Rep_Title1, C_MSE_Rewards_Type1, C_Wiz_Loyalty_Level1, C_Package_Tracking_Number1, C_MSE_RepTM_Link_11, C_Gift_Tracking__11, C_MSE_Focus_Group_Time1, C_AB_Randomized1, C_Automation_Yes1_No01, C_LinkedIn_Profile1, C_Facebook_Profile1, C_Ticket_Type1, C_MSE_Renewal_Status1, C_AFL___Sales_Rep_Full_Name1, C_AFL___Sales_Rep_Email1, C_AFL___Sales_Rep_First_Name1, C_AFL___Sales_Rep_Last_Name1, C_AFL___Sales_Rep_Phone1, C_AFL___Sales_Rep_Title1, C_Seat_Number1, C_MSE_Team1
	, ROW_NUMBER() OVER(PARTITION BY ID ORDER BY ETL_ID) RowRank
	FROM stg.Eloqua_Contact
) a
WHERE RowRank = 1;


UPDATE #SrcData
SET ETL_DeltaHashKey = HASHBYTES('sha2_256', ISNULL(RTRIM(CONVERT(varchar(25),AccessedAt)),'DBNULL_DATETIME') + ISNULL(RTRIM(AccountName),'DBNULL_TEXT') + ISNULL(RTRIM(Address1),'DBNULL_TEXT') + ISNULL(RTRIM(Address2),'DBNULL_TEXT') + ISNULL(RTRIM(Address3),'DBNULL_TEXT') + ISNULL(RTRIM(BouncebackDate),'DBNULL_TEXT') + ISNULL(RTRIM(BusinessPhone),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C___of_Times_Downloaded_High_Valued_Content__)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(25),C___of_Times_Downloaded_High_Valued_Content__3)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(25),C___of_Times_Downloaded_High_Valued_Content__4)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(25),C___Times_Viewed_High_Value_Content___ALL1)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_2011_12_Sales_Pack_Interest1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_AB_Randomized1)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_Account),'DBNULL_TEXT') + ISNULL(RTRIM(C_Acct_Type_Desc1),'DBNULL_TEXT') + ISNULL(RTRIM(C_AFL___Sales_Rep_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_AFL___Sales_Rep_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_AFL___Sales_Rep_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_AFL___Sales_Rep_Last_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_AFL___Sales_Rep_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_AFL___Sales_Rep_Title1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Alt_Address_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Alt_Address_21),'DBNULL_TEXT') + ISNULL(RTRIM(C_Alt_City1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Alt_Company1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Alt_Country1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Alt_State1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Alt_Zip_Code1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Annual_Revenue1)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(25),C_Annual_Sales)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_Annual_Sales_Indicator),'DBNULL_TEXT') + ISNULL(RTRIM(C_Attention_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Automation_Yes1_No01)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_B2C___Lead_Rating___Combined1),'DBNULL_TEXT') + ISNULL(RTRIM(C_B2C___Lead_Rating___Explicit1),'DBNULL_TEXT') + ISNULL(RTRIM(C_B2C___Lead_Rating___Implicit1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_B2C___Lead_Score___Explicit1)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(25),C_B2C___Lead_Score___High_Value_Website_Conte)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(25),C_B2C___Lead_Score___Implicit1)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(10),C_B2C___Lead_Score_Date___Most_Recent1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Best_Time_to_Conact1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Birthdate_C1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Birthdate_M1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Birthdate_W1,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_Birthdate1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Caps___12_13_Par__STH__Dep__Premium_Renewal),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps___Holiday_PURL1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps___Kids_Club_Expire_Date1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps___Number_Attending1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps___SAS_Timeslot1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps___STH_Presale_Time1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_201516_Renewal_PURL1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Balance_Due1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Canopy_Data1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Decline_Amount_Due1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Focus_Group_Time1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_GS_Rep_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_GS_Rep_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_GS_Rep_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_GS_Rep_Last_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_GS_Rep_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_GS_Rep_Title1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Kids_Club_Referral_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Kids_Club1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Non_Renewed_Rep1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Number_of_Group_Games1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Number_of_Group_Seats1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Promo_Code_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_PURL_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_RepTM_Link_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Sales_Rep_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Sales_Rep_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Sales_Rep_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Sales_Rep_Last_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Sales_Rep_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_Sales_Rep_Title1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_STH_Loyalty1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Caps_TA_and_IC_Opt_Ins1),'DBNULL_TEXT') + ISNULL(RTRIM(C_CC_Expiration1),'DBNULL_TEXT') + ISNULL(RTRIM(C_CC_Type1),'DBNULL_TEXT') + ISNULL(RTRIM(C_CEO_Name),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Child_1_Birthday1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Child_11),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Child_2_Birthday1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Child_21),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Child_3_Birthday1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Child_31),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Child_4_Birthday1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Child_41),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Child_5_Birthday1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Child_51),'DBNULL_TEXT') + ISNULL(RTRIM(C_Company_Revenue1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Contact_Preference_for_Sales1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_DateCreated,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_DateModified,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Daytime_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Decline_Amount_Due1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Discretionary_Income1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Doing_Business_As),'DBNULL_TEXT') + ISNULL(RTRIM(C_DUNS_Number),'DBNULL_TEXT') + ISNULL(RTRIM(C_ElqPURLName),'DBNULL_TEXT') + ISNULL(RTRIM(C_elqPURLName1),'DBNULL_TEXT') + ISNULL(RTRIM(C_elqPURLName3),'DBNULL_TEXT') + ISNULL(RTRIM(C_elqPURLName4),'DBNULL_TEXT') + ISNULL(RTRIM(C_elqPURLName5),'DBNULL_TEXT') + ISNULL(RTRIM(C_elqPURLName6),'DBNULL_TEXT') + ISNULL(RTRIM(C_Email_Opt_In1),'DBNULL_TEXT') + ISNULL(RTRIM(C_EmailAddressDomain),'DBNULL_TEXT') + ISNULL(RTRIM(C_Established_In),'DBNULL_TEXT') + ISNULL(RTRIM(C_Evening_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Executive_Suite_Interest1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Facebook_Profile1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Favorite_Player1),'DBNULL_TEXT') + ISNULL(RTRIM(C_FirstAndLastName),'DBNULL_TEXT') + ISNULL(RTRIM(C_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Gender1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Gift_Tracking__11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Group_Size_Interest1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Guest_Services_Rep1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Guest_Services_Reps_II1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Household_Income1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Industry),'DBNULL_TEXT') + ISNULL(RTRIM(C_Industry1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Integrated_Marketing_and_Sales_Funnel_Stage),'DBNULL_TEXT') + ISNULL(RTRIM(C_Interests1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Job_Role1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Last_4_CC_Digits1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Last_Lead_Rating1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Last_Lead_Score1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Last_Single_Game_Ticket_Purchase_Date1,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_Last_Website_Visit_Date_and_Time1,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_LastModifiedByExtIntegrateSystem,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Lead_Rating___Combined1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Rating___Historical_All_Time__HAT_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Score),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Lead_Score___Historical_All_Time1)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(10),C_Lead_Score___Last_High_Touch_Event_Date1,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_Lead_Score_Date___Most_Recent1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Lead_Source___Most_Recent1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Source___Original1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Status1),'DBNULL_TEXT') + ISNULL(RTRIM(C_LinkedIn_Profile1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_LS___High_Value_Website_Content1)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_MD5HashedBusPhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_MD5HashedEmailAddress),'DBNULL_TEXT') + ISNULL(RTRIM(C_MD5HashedMobilePhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mobile_Opt_In1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Most_Recent_Form_Submitted1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_____of_Rewards_Logins1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE___Accrued_Rewards_Points1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE___Current_Rewards_Points1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_MSE___Last_Rewards_Login1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_MSE___Spent_Rewards_Points1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Account_ID1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Balance_Due1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Canopy_Data1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Decline_Amount_Due1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Focus_Group_Time1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Number_of_Group_Games1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Number_of_Group_Seats1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Renewal_Status1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_RepTM_Link_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Rewards_Amount1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Rewards_Type1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Sales_Rep_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Sales_Rep_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Sales_Rep_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Sales_Rep_Last_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Sales_Rep_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Sales_Rep_Title1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_STH_Presale_Timeslot1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSE_Team1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Balance_Due1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Canopy_Data1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Decline_Amount_Due1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_GS_Rep_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_GS_Rep_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_GS_Rep_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_GS_Rep_Last_name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_GS_Rep_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_GS_Rep_Title1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Number_of_Group_Games1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Number_of_Group_Seats1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Promo_Code_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_PURL_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_RepTM_Link_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Sales_Rep_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Sales_Rep_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Sales_Rep_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Sales_Rep_Last_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Sales_Rep_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_Sales_Rep_Title1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mys_STH_Presale_Timeslot1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mystics_Account_ID1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Name_Last1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Number_of_Employees1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Number_of_Seats1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Package_Interest1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Package_Tracking_Number1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Past_Purchases__Suite___Sponsorships_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Payment_Memo_Code1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Premium_Package_Rep1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Previous_Purchase1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Product_Solution_of_Interest1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Purchase_History___Most_Recent1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Question_Comments1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Referred_by_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Referred_by_Last_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Region1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Renewal_Memo_Code1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Rep_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Rep_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Rep_Title1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Row1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Sales_Rep_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Salutation),'DBNULL_TEXT') + ISNULL(RTRIM(C_Season_Ticket_Holder1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Season1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Seat_Number1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Section1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Select_a_seat_2011_12_Yes_No1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_EmailOptOut1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_Interests1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_Lead_Rating1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_Ticket___Archtics_ID1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_Ticket___Event_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_Ticket___First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_Ticket___Price_Code1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_SFDC_Ticket___Purchase_Date1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_SFDC_Ticket___Purchase_Price1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_Ticket___Purchase_Qty1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_Ticket___Rep_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCAccountID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCContactID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCLastCampaignID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCLastCampaignName),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCLastCampaignStatus),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCLeadID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SHA256HashedBusPhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_SHA256HashedEmailAddress),'DBNULL_TEXT') + ISNULL(RTRIM(C_SHA256HashedMobilePhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_SIC_Code),'DBNULL_TEXT') + ISNULL(RTRIM(C_State_Prov),'DBNULL_TEXT') + ISNULL(RTRIM(C_STH_Since_Date__Caps1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Suite__1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Suite_Facility1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Suite_Seats1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Suites___Rep_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Territory),'DBNULL_TEXT') + ISNULL(RTRIM(C_Ticket_Type1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Total_Employees)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_Total_Employees_Indicator),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Total_Visits1)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_Turnkey_Rating___Score1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Twitter_Handle1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Type_of_Mobile_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Website),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz___Balance_Due1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz___Canopy_Data1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz___Guest_Services_Reps1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz___Holiday_E_Card_Purl1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz___Holiday_Pack_Game_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz___Holiday_Pack_Game_21),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Wiz___PG_Event_Date1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Wiz___PG_Event_Opponent1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz___PG_Season_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz___Promo_Code1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz___STH_Presale_Timeslot1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_Decline_Amount_Due1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_Focus_Group_Time1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_GS_Rep_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_GS_Rep_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_GS_Rep_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_GS_Rep_Last_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_GS_Rep_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_GS_Rep_Title1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_Loyalty_Level1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_Number_of_Group_Games1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_Number_of_Group_Seats1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_PURL_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_RepTM_Link_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_Sales_Rep_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_Sales_Rep_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_Sales_Rep_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_Sales_Rep_Last_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_Sales_Rep_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wiz_Sales_Rep_Title1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Wizards_Account_ID1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Zip_Code__Georgraphic_Area_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Zip_Postal),'DBNULL_TEXT') + ISNULL(RTRIM(City),'DBNULL_TEXT') + ISNULL(RTRIM(Company),'DBNULL_TEXT') + ISNULL(RTRIM(ContactIDExt),'DBNULL_TEXT') + ISNULL(RTRIM(Country),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),CreatedAt)),'DBNULL_DATETIME') + ISNULL(RTRIM(CreatedBy),'DBNULL_TEXT') + ISNULL(RTRIM(CurrentStatus),'DBNULL_TEXT') + ISNULL(RTRIM(Depth),'DBNULL_TEXT') + ISNULL(RTRIM(EmailAddress),'DBNULL_TEXT') + ISNULL(RTRIM(Fax),'DBNULL_TEXT') + ISNULL(RTRIM(FirstName),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),ID)),'DBNULL_INT') + ISNULL(RTRIM(CONVERT(varchar(10),IsBounceback)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),IsSubscribed)),'DBNULL_BIT') + ISNULL(RTRIM(LastName),'DBNULL_TEXT') + ISNULL(RTRIM(MobilePhone),'DBNULL_TEXT') + ISNULL(RTRIM(Name),'DBNULL_TEXT') + ISNULL(RTRIM(PostalCode),'DBNULL_TEXT') + ISNULL(RTRIM(Province),'DBNULL_TEXT') + ISNULL(RTRIM(SalesPerson),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),SubscriptionDate)),'DBNULL_DATETIME') + ISNULL(RTRIM(Title),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),UnsubscriptionDate)),'DBNULL_DATETIME') + ISNULL(RTRIM(CONVERT(varchar(25),UpdatedAt)),'DBNULL_DATETIME') + ISNULL(RTRIM(UpdatedBy),'DBNULL_TEXT'));


CREATE NONCLUSTERED INDEX IDX_BusinessKey_HashKey ON #SrcData (ID,ETL_DeltaHashKey);

--	remove existing, unchanged records from #SrcData
DELETE A
FROM #SrcData A
JOIN ods.Eloqua_Contact B
	ON A.ID = B.ID
	AND A.ETL_DeltaHashKey = B.ETL_DeltaHashKey;


CREATE NONCLUSTERED INDEX IDX_Load_Key ON #SrcData (ID);
CREATE NONCLUSTERED INDEX IDX_ETL_DeltaHashKey ON #SrcData (ETL_DeltaHashKey);


UPDATE myTarget
SET    myTarget.[ETL_UpdatedDate] = @RunTime
     , myTarget.[ETL_IsDeleted] = 0
     , myTarget.[ETL_DeletedDate] = NULL
     , myTarget.[ETL_DeltaHashKey] = mySource.[ETL_DeltaHashKey]
     , myTarget.[ID] = mySource.[ID]
     , myTarget.[Name] = mySource.[Name]
     , myTarget.[AccountName] = mySource.[AccountName]
     , myTarget.[BouncebackDate] = mySource.[BouncebackDate]
     , myTarget.[IsBounceback] = mySource.[IsBounceback]
     , myTarget.[IsSubscribed] = mySource.[IsSubscribed]
     , myTarget.[PostalCode] = mySource.[PostalCode]
     , myTarget.[Province] = mySource.[Province]
     , myTarget.[SubscriptionDate] = mySource.[SubscriptionDate]
     , myTarget.[UnsubscriptionDate] = mySource.[UnsubscriptionDate]
     , myTarget.[CreatedAt] = mySource.[CreatedAt]
     , myTarget.[CreatedBy] = mySource.[CreatedBy]
     , myTarget.[AccessedAt] = mySource.[AccessedAt]
     , myTarget.[CurrentStatus] = mySource.[CurrentStatus]
     , myTarget.[Depth] = mySource.[Depth]
     , myTarget.[UpdatedAt] = mySource.[UpdatedAt]
     , myTarget.[UpdatedBy] = mySource.[UpdatedBy]
     , myTarget.[EmailAddress] = mySource.[EmailAddress]
     , myTarget.[FirstName] = mySource.[FirstName]
     , myTarget.[LastName] = mySource.[LastName]
     , myTarget.[Company] = mySource.[Company]
     , myTarget.[Address1] = mySource.[Address1]
     , myTarget.[Address2] = mySource.[Address2]
     , myTarget.[Address3] = mySource.[Address3]
     , myTarget.[City] = mySource.[City]
     , myTarget.[Country] = mySource.[Country]
     , myTarget.[MobilePhone] = mySource.[MobilePhone]
     , myTarget.[BusinessPhone] = mySource.[BusinessPhone]
     , myTarget.[Fax] = mySource.[Fax]
     , myTarget.[Title] = mySource.[Title]
     , myTarget.[SalesPerson] = mySource.[SalesPerson]
     , myTarget.[C_State_Prov] = mySource.[C_State_Prov]
     , myTarget.[C_Zip_Postal] = mySource.[C_Zip_Postal]
     , myTarget.[C_Salutation] = mySource.[C_Salutation]
     , myTarget.[C_Account] = mySource.[C_Account]
     , myTarget.[C_SFDCContactID] = mySource.[C_SFDCContactID]
     , myTarget.[C_SFDCLeadID] = mySource.[C_SFDCLeadID]
     , myTarget.[C_Website] = mySource.[C_Website]
     , myTarget.[C_DateCreated] = mySource.[C_DateCreated]
     , myTarget.[C_DateModified] = mySource.[C_DateModified]
     , myTarget.[ContactIDExt] = mySource.[ContactIDExt]
     , myTarget.[C_SFDCAccountID] = mySource.[C_SFDCAccountID]
     , myTarget.[C_LastModifiedByExtIntegrateSystem] = mySource.[C_LastModifiedByExtIntegrateSystem]
     , myTarget.[C_SFDCLastCampaignID] = mySource.[C_SFDCLastCampaignID]
     , myTarget.[C_SFDCLastCampaignStatus] = mySource.[C_SFDCLastCampaignStatus]
     , myTarget.[C_Last_Lead_Rating1] = mySource.[C_Last_Lead_Rating1]
     , myTarget.[C_Last_Lead_Score1] = mySource.[C_Last_Lead_Score1]
     , myTarget.[C_Lead_Score___Historical_All_Time1] = mySource.[C_Lead_Score___Historical_All_Time1]
     , myTarget.[C_Lead_Rating___Historical_All_Time__HAT_1] = mySource.[C_Lead_Rating___Historical_All_Time__HAT_1]
     , myTarget.[C_Company_Revenue1] = mySource.[C_Company_Revenue1]
     , myTarget.[C_SFDC_EmailOptOut1] = mySource.[C_SFDC_EmailOptOut1]
     , myTarget.[C_Lead_Source___Most_Recent1] = mySource.[C_Lead_Source___Most_Recent1]
     , myTarget.[C_Lead_Source___Original1] = mySource.[C_Lead_Source___Original1]
     , myTarget.[C_Industry1] = mySource.[C_Industry1]
     , myTarget.[C_Lead_Status1] = mySource.[C_Lead_Status1]
     , myTarget.[C_Job_Role1] = mySource.[C_Job_Role1]
     , myTarget.[C_Last_Website_Visit_Date_and_Time1] = mySource.[C_Last_Website_Visit_Date_and_Time1]
     , myTarget.[C_LS___High_Value_Website_Content1] = mySource.[C_LS___High_Value_Website_Content1]
     , myTarget.[C_DUNS_Number] = mySource.[C_DUNS_Number]
     , myTarget.[C_Doing_Business_As] = mySource.[C_Doing_Business_As]
     , myTarget.[C_CEO_Name] = mySource.[C_CEO_Name]
     , myTarget.[C_Industry] = mySource.[C_Industry]
     , myTarget.[C_SIC_Code] = mySource.[C_SIC_Code]
     , myTarget.[C_Established_In] = mySource.[C_Established_In]
     , myTarget.[C_Annual_Sales_Indicator] = mySource.[C_Annual_Sales_Indicator]
     , myTarget.[C_Annual_Sales] = mySource.[C_Annual_Sales]
     , myTarget.[C_Total_Employees] = mySource.[C_Total_Employees]
     , myTarget.[C_Total_Employees_Indicator] = mySource.[C_Total_Employees_Indicator]
     , myTarget.[C_Lead_Score_Date___Most_Recent1] = mySource.[C_Lead_Score_Date___Most_Recent1]
     , myTarget.[C_Integrated_Marketing_and_Sales_Funnel_Stage] = mySource.[C_Integrated_Marketing_and_Sales_Funnel_Stage]
     , myTarget.[C_Product_Solution_of_Interest1] = mySource.[C_Product_Solution_of_Interest1]
     , myTarget.[C_Region1] = mySource.[C_Region1]
     , myTarget.[C_elqPURLName1] = mySource.[C_elqPURLName1]
     , myTarget.[C_Most_Recent_Form_Submitted1] = mySource.[C_Most_Recent_Form_Submitted1]
     , myTarget.[C_Household_Income1] = mySource.[C_Household_Income1]
     , myTarget.[C___of_Times_Downloaded_High_Valued_Content__] = mySource.[C___of_Times_Downloaded_High_Valued_Content__]
     , myTarget.[C___of_Times_Downloaded_High_Valued_Content__3] = mySource.[C___of_Times_Downloaded_High_Valued_Content__3]
     , myTarget.[C___of_Times_Downloaded_High_Valued_Content__4] = mySource.[C___of_Times_Downloaded_High_Valued_Content__4]
     , myTarget.[C_Lead_Rating___Combined1] = mySource.[C_Lead_Rating___Combined1]
     , myTarget.[C_Purchase_History___Most_Recent1] = mySource.[C_Purchase_History___Most_Recent1]
     , myTarget.[C___Times_Viewed_High_Value_Content___ALL1] = mySource.[C___Times_Viewed_High_Value_Content___ALL1]
     , myTarget.[C_Total_Visits1] = mySource.[C_Total_Visits1]
     , myTarget.[C_Daytime_Phone1] = mySource.[C_Daytime_Phone1]
     , myTarget.[C_Evening_Phone1] = mySource.[C_Evening_Phone1]
     , myTarget.[C_Name_Last1] = mySource.[C_Name_Last1]
     , myTarget.[C_Acct_Type_Desc1] = mySource.[C_Acct_Type_Desc1]
     , myTarget.[C_Email_Opt_In1] = mySource.[C_Email_Opt_In1]
     , myTarget.[C_Birthdate1] = mySource.[C_Birthdate1]
     , myTarget.[C_Favorite_Player1] = mySource.[C_Favorite_Player1]
     , myTarget.[C_elqPURLName3] = mySource.[C_elqPURLName3]
     , myTarget.[C_EmailAddressDomain] = mySource.[C_EmailAddressDomain]
     , myTarget.[C_FirstAndLastName] = mySource.[C_FirstAndLastName]
     , myTarget.[C_Best_Time_to_Conact1] = mySource.[C_Best_Time_to_Conact1]
     , myTarget.[C_Mobile_Opt_In1] = mySource.[C_Mobile_Opt_In1]
     , myTarget.[C_Guest_Services_Rep1] = mySource.[C_Guest_Services_Rep1]
     , myTarget.[C_Phone1] = mySource.[C_Phone1]
     , myTarget.[C_Season1] = mySource.[C_Season1]
     , myTarget.[C_Gender1] = mySource.[C_Gender1]
     , myTarget.[C_Renewal_Memo_Code1] = mySource.[C_Renewal_Memo_Code1]
     , myTarget.[C_Payment_Memo_Code1] = mySource.[C_Payment_Memo_Code1]
     , myTarget.[C_Number_of_Seats1] = mySource.[C_Number_of_Seats1]
     , myTarget.[C_Select_a_seat_2011_12_Yes_No1] = mySource.[C_Select_a_seat_2011_12_Yes_No1]
     , myTarget.[C_2011_12_Sales_Pack_Interest1] = mySource.[C_2011_12_Sales_Pack_Interest1]
     , myTarget.[C_Contact_Preference_for_Sales1] = mySource.[C_Contact_Preference_for_Sales1]
     , myTarget.[C_Executive_Suite_Interest1] = mySource.[C_Executive_Suite_Interest1]
     , myTarget.[C_Group_Size_Interest1] = mySource.[C_Group_Size_Interest1]
     , myTarget.[C_Attention_Name1] = mySource.[C_Attention_Name1]
     , myTarget.[C_Alt_Address_11] = mySource.[C_Alt_Address_11]
     , myTarget.[C_Alt_Address_21] = mySource.[C_Alt_Address_21]
     , myTarget.[C_Alt_City1] = mySource.[C_Alt_City1]
     , myTarget.[C_Alt_Zip_Code1] = mySource.[C_Alt_Zip_Code1]
     , myTarget.[C_Alt_State1] = mySource.[C_Alt_State1]
     , myTarget.[C_Alt_Company1] = mySource.[C_Alt_Company1]
     , myTarget.[C_SFDCLastCampaignName] = mySource.[C_SFDCLastCampaignName]
     , myTarget.[C_SFDC_Lead_Rating1] = mySource.[C_SFDC_Lead_Rating1]
     , myTarget.[C_Caps_STH_Loyalty1] = mySource.[C_Caps_STH_Loyalty1]
     , myTarget.[C_Guest_Services_Reps_II1] = mySource.[C_Guest_Services_Reps_II1]
     , myTarget.[C_elqPURLName4] = mySource.[C_elqPURLName4]
     , myTarget.[C_elqPURLName5] = mySource.[C_elqPURLName5]
     , myTarget.[C_elqPURLName6] = mySource.[C_elqPURLName6]
     , myTarget.[C_SFDC_Interests1] = mySource.[C_SFDC_Interests1]
     , myTarget.[C_Suite_Facility1] = mySource.[C_Suite_Facility1]
     , myTarget.[C_Suite__1] = mySource.[C_Suite__1]
     , myTarget.[C_Suite_Seats1] = mySource.[C_Suite_Seats1]
     , myTarget.[C_Lead_Score___Last_High_Touch_Event_Date1] = mySource.[C_Lead_Score___Last_High_Touch_Event_Date1]
     , myTarget.[C_Last_Single_Game_Ticket_Purchase_Date1] = mySource.[C_Last_Single_Game_Ticket_Purchase_Date1]
     , myTarget.[C_B2C___Lead_Rating___Combined1] = mySource.[C_B2C___Lead_Rating___Combined1]
     , myTarget.[C_B2C___Lead_Rating___Explicit1] = mySource.[C_B2C___Lead_Rating___Explicit1]
     , myTarget.[C_B2C___Lead_Score___Explicit1] = mySource.[C_B2C___Lead_Score___Explicit1]
     , myTarget.[C_B2C___Lead_Rating___Implicit1] = mySource.[C_B2C___Lead_Rating___Implicit1]
     , myTarget.[C_B2C___Lead_Score___High_Value_Website_Conte] = mySource.[C_B2C___Lead_Score___High_Value_Website_Conte]
     , myTarget.[C_B2C___Lead_Score___Implicit1] = mySource.[C_B2C___Lead_Score___Implicit1]
     , myTarget.[C_B2C___Lead_Score_Date___Most_Recent1] = mySource.[C_B2C___Lead_Score_Date___Most_Recent1]
     , myTarget.[C_Number_of_Employees1] = mySource.[C_Number_of_Employees1]
     , myTarget.[C_Past_Purchases__Suite___Sponsorships_1] = mySource.[C_Past_Purchases__Suite___Sponsorships_1]
     , myTarget.[C_Zip_Code__Georgraphic_Area_1] = mySource.[C_Zip_Code__Georgraphic_Area_1]
     , myTarget.[C_Previous_Purchase1] = mySource.[C_Previous_Purchase1]
     , myTarget.[C_Discretionary_Income1] = mySource.[C_Discretionary_Income1]
     , myTarget.[C_Wizards_Account_ID1] = mySource.[C_Wizards_Account_ID1]
     , myTarget.[C_Mystics_Account_ID1] = mySource.[C_Mystics_Account_ID1]
     , myTarget.[C_Interests1] = mySource.[C_Interests1]
     , myTarget.[C_Annual_Revenue1] = mySource.[C_Annual_Revenue1]
     , myTarget.[C_Turnkey_Rating___Score1] = mySource.[C_Turnkey_Rating___Score1]
     , myTarget.[C_Child_11] = mySource.[C_Child_11]
     , myTarget.[C_Child_21] = mySource.[C_Child_21]
     , myTarget.[C_Child_31] = mySource.[C_Child_31]
     , myTarget.[C_Season_Ticket_Holder1] = mySource.[C_Season_Ticket_Holder1]
     , myTarget.[C_Wiz___Balance_Due1] = mySource.[C_Wiz___Balance_Due1]
     , myTarget.[C_Wiz___Guest_Services_Reps1] = mySource.[C_Wiz___Guest_Services_Reps1]
     , myTarget.[C_Child_41] = mySource.[C_Child_41]
     , myTarget.[C_Child_51] = mySource.[C_Child_51]
     , myTarget.[C_Child_2_Birthday1] = mySource.[C_Child_2_Birthday1]
     , myTarget.[C_Child_1_Birthday1] = mySource.[C_Child_1_Birthday1]
     , myTarget.[C_Caps_Kids_Club1] = mySource.[C_Caps_Kids_Club1]
     , myTarget.[C_Caps_Kids_Club_Referral_Email1] = mySource.[C_Caps_Kids_Club_Referral_Email1]
     , myTarget.[C_Birthdate_C1] = mySource.[C_Birthdate_C1]
     , myTarget.[C_Birthdate_W1] = mySource.[C_Birthdate_W1]
     , myTarget.[C_Birthdate_M1] = mySource.[C_Birthdate_M1]
     , myTarget.[C_Type_of_Mobile_Phone1] = mySource.[C_Type_of_Mobile_Phone1]
     , myTarget.[C_Caps___12_13_Par__STH__Dep__Premium_Renewal] = mySource.[C_Caps___12_13_Par__STH__Dep__Premium_Renewal]
     , myTarget.[C_Rep_Phone1] = mySource.[C_Rep_Phone1]
     , myTarget.[C_Rep_Email1] = mySource.[C_Rep_Email1]
     , myTarget.[C_Package_Interest1] = mySource.[C_Package_Interest1]
     , myTarget.[C_Question_Comments1] = mySource.[C_Question_Comments1]
     , myTarget.[C_Premium_Package_Rep1] = mySource.[C_Premium_Package_Rep1]
     , myTarget.[C_Caps_Non_Renewed_Rep1] = mySource.[C_Caps_Non_Renewed_Rep1]
     , myTarget.[C_Referred_by_First_Name1] = mySource.[C_Referred_by_First_Name1]
     , myTarget.[C_Referred_by_Last_Name1] = mySource.[C_Referred_by_Last_Name1]
     , myTarget.[C_Territory] = mySource.[C_Territory]
     , myTarget.[C_SFDC_Ticket___Rep_Name1] = mySource.[C_SFDC_Ticket___Rep_Name1]
     , myTarget.[C_SFDC_Ticket___Price_Code1] = mySource.[C_SFDC_Ticket___Price_Code1]
     , myTarget.[C_SFDC_Ticket___Event_Name1] = mySource.[C_SFDC_Ticket___Event_Name1]
     , myTarget.[C_SFDC_Ticket___Purchase_Qty1] = mySource.[C_SFDC_Ticket___Purchase_Qty1]
     , myTarget.[C_SFDC_Ticket___Purchase_Price1] = mySource.[C_SFDC_Ticket___Purchase_Price1]
     , myTarget.[C_SFDC_Ticket___Archtics_ID1] = mySource.[C_SFDC_Ticket___Archtics_ID1]
     , myTarget.[C_SFDC_Ticket___Purchase_Date1] = mySource.[C_SFDC_Ticket___Purchase_Date1]
     , myTarget.[C_SFDC_Ticket___First_Name1] = mySource.[C_SFDC_Ticket___First_Name1]
     , myTarget.[C_Caps___Holiday_PURL1] = mySource.[C_Caps___Holiday_PURL1]
     , myTarget.[C_Wiz___Holiday_E_Card_Purl1] = mySource.[C_Wiz___Holiday_E_Card_Purl1]
     , myTarget.[C_Wiz___Holiday_Pack_Game_11] = mySource.[C_Wiz___Holiday_Pack_Game_11]
     , myTarget.[C_Wiz___Holiday_Pack_Game_21] = mySource.[C_Wiz___Holiday_Pack_Game_21]
     , myTarget.[C_Lead_Score] = mySource.[C_Lead_Score]
     , myTarget.[C_ElqPURLName] = mySource.[C_ElqPURLName]
     , myTarget.[C_Suites___Rep_Name1] = mySource.[C_Suites___Rep_Name1]
     , myTarget.[C_Caps___STH_Presale_Time1] = mySource.[C_Caps___STH_Presale_Time1]
     , myTarget.[C_Caps_TA_and_IC_Opt_Ins1] = mySource.[C_Caps_TA_and_IC_Opt_Ins1]
     , myTarget.[C_Twitter_Handle1] = mySource.[C_Twitter_Handle1]
     , myTarget.[C_Sales_Rep_First_Name1] = mySource.[C_Sales_Rep_First_Name1]
     , myTarget.[C_Full_Name1] = mySource.[C_Full_Name1]
     , myTarget.[C_MSE_Account_ID1] = mySource.[C_MSE_Account_ID1]
     , myTarget.[C_Last_4_CC_Digits1] = mySource.[C_Last_4_CC_Digits1]
     , myTarget.[C_CC_Type1] = mySource.[C_CC_Type1]
     , myTarget.[C_CC_Expiration1] = mySource.[C_CC_Expiration1]
     , myTarget.[C_Rep_Title1] = mySource.[C_Rep_Title1]
     , myTarget.[C_Decline_Amount_Due1] = mySource.[C_Decline_Amount_Due1]
     , myTarget.[C_Wiz___Canopy_Data1] = mySource.[C_Wiz___Canopy_Data1]
     , myTarget.[C_MSE_Rewards_Amount1] = mySource.[C_MSE_Rewards_Amount1]
     , myTarget.[C_Wiz___PG_Season_Name1] = mySource.[C_Wiz___PG_Season_Name1]
     , myTarget.[C_Wiz___PG_Event_Opponent1] = mySource.[C_Wiz___PG_Event_Opponent1]
     , myTarget.[C_Wiz___PG_Event_Date1] = mySource.[C_Wiz___PG_Event_Date1]
     , myTarget.[C_MSE___Current_Rewards_Points1] = mySource.[C_MSE___Current_Rewards_Points1]
     , myTarget.[C_MSE___Accrued_Rewards_Points1] = mySource.[C_MSE___Accrued_Rewards_Points1]
     , myTarget.[C_MSE_____of_Rewards_Logins1] = mySource.[C_MSE_____of_Rewards_Logins1]
     , myTarget.[C_MSE___Last_Rewards_Login1] = mySource.[C_MSE___Last_Rewards_Login1]
     , myTarget.[C_MSE___Spent_Rewards_Points1] = mySource.[C_MSE___Spent_Rewards_Points1]
     , myTarget.[C_Wiz___STH_Presale_Timeslot1] = mySource.[C_Wiz___STH_Presale_Timeslot1]
     , myTarget.[C_MD5HashedEmailAddress] = mySource.[C_MD5HashedEmailAddress]
     , myTarget.[C_SHA256HashedEmailAddress] = mySource.[C_SHA256HashedEmailAddress]
     , myTarget.[C_MD5HashedBusPhone] = mySource.[C_MD5HashedBusPhone]
     , myTarget.[C_SHA256HashedBusPhone] = mySource.[C_SHA256HashedBusPhone]
     , myTarget.[C_MD5HashedMobilePhone] = mySource.[C_MD5HashedMobilePhone]
     , myTarget.[C_SHA256HashedMobilePhone] = mySource.[C_SHA256HashedMobilePhone]
     , myTarget.[C_Wiz___Promo_Code1] = mySource.[C_Wiz___Promo_Code1]
     , myTarget.[C_Caps_201516_Renewal_PURL1] = mySource.[C_Caps_201516_Renewal_PURL1]
     , myTarget.[C_Caps___Kids_Club_Expire_Date1] = mySource.[C_Caps___Kids_Club_Expire_Date1]
     , myTarget.[C_Caps___SAS_Timeslot1] = mySource.[C_Caps___SAS_Timeslot1]
     , myTarget.[C_STH_Since_Date__Caps1] = mySource.[C_STH_Since_Date__Caps1]
     , myTarget.[C_Caps_Sales_Rep_Full_Name1] = mySource.[C_Caps_Sales_Rep_Full_Name1]
     , myTarget.[C_Caps_Sales_Rep_First_Name1] = mySource.[C_Caps_Sales_Rep_First_Name1]
     , myTarget.[C_Caps_Sales_Rep_Last_Name1] = mySource.[C_Caps_Sales_Rep_Last_Name1]
     , myTarget.[C_Caps_Sales_Rep_Email1] = mySource.[C_Caps_Sales_Rep_Email1]
     , myTarget.[C_Caps_Sales_Rep_Phone1] = mySource.[C_Caps_Sales_Rep_Phone1]
     , myTarget.[C_Caps_Sales_Rep_Title1] = mySource.[C_Caps_Sales_Rep_Title1]
     , myTarget.[C_Wiz_Sales_Rep_Full_Name1] = mySource.[C_Wiz_Sales_Rep_Full_Name1]
     , myTarget.[C_Wiz_Sales_Rep_First_Name1] = mySource.[C_Wiz_Sales_Rep_First_Name1]
     , myTarget.[C_Wiz_Sales_Rep_Last_Name1] = mySource.[C_Wiz_Sales_Rep_Last_Name1]
     , myTarget.[C_Wiz_Sales_Rep_Email1] = mySource.[C_Wiz_Sales_Rep_Email1]
     , myTarget.[C_Wiz_Sales_Rep_Phone1] = mySource.[C_Wiz_Sales_Rep_Phone1]
     , myTarget.[C_Wiz_Sales_Rep_Title1] = mySource.[C_Wiz_Sales_Rep_Title1]
     , myTarget.[C_Mys_Sales_Rep_Full_Name1] = mySource.[C_Mys_Sales_Rep_Full_Name1]
     , myTarget.[C_Mys_Sales_Rep_First_Name1] = mySource.[C_Mys_Sales_Rep_First_Name1]
     , myTarget.[C_Mys_Sales_Rep_Last_Name1] = mySource.[C_Mys_Sales_Rep_Last_Name1]
     , myTarget.[C_Mys_Sales_Rep_Email1] = mySource.[C_Mys_Sales_Rep_Email1]
     , myTarget.[C_Mys_Sales_Rep_Phone1] = mySource.[C_Mys_Sales_Rep_Phone1]
     , myTarget.[C_Mys_Sales_Rep_Title1] = mySource.[C_Mys_Sales_Rep_Title1]
     , myTarget.[C_MSE_Sales_Rep_Full_Name1] = mySource.[C_MSE_Sales_Rep_Full_Name1]
     , myTarget.[C_MSE_Sales_Rep_First_Name1] = mySource.[C_MSE_Sales_Rep_First_Name1]
     , myTarget.[C_MSE_Sales_Rep_Last_Name1] = mySource.[C_MSE_Sales_Rep_Last_Name1]
     , myTarget.[C_MSE_Sales_Rep_Email1] = mySource.[C_MSE_Sales_Rep_Email1]
     , myTarget.[C_MSE_Sales_Rep_Phone1] = mySource.[C_MSE_Sales_Rep_Phone1]
     , myTarget.[C_MSE_Sales_Rep_Title1] = mySource.[C_MSE_Sales_Rep_Title1]
     , myTarget.[C_Alt_Country1] = mySource.[C_Alt_Country1]
     , myTarget.[C_Caps_RepTM_Link_11] = mySource.[C_Caps_RepTM_Link_11]
     , myTarget.[C_Wiz_RepTM_Link_11] = mySource.[C_Wiz_RepTM_Link_11]
     , myTarget.[C_Mys_RepTM_Link_11] = mySource.[C_Mys_RepTM_Link_11]
     , myTarget.[C_Caps_PURL_11] = mySource.[C_Caps_PURL_11]
     , myTarget.[C_Wiz_PURL_11] = mySource.[C_Wiz_PURL_11]
     , myTarget.[C_Mys_PURL_11] = mySource.[C_Mys_PURL_11]
     , myTarget.[C_Mys_STH_Presale_Timeslot1] = mySource.[C_Mys_STH_Presale_Timeslot1]
     , myTarget.[C_MSE_STH_Presale_Timeslot1] = mySource.[C_MSE_STH_Presale_Timeslot1]
     , myTarget.[C_Caps_Promo_Code_11] = mySource.[C_Caps_Promo_Code_11]
     , myTarget.[C_Mys_Promo_Code_11] = mySource.[C_Mys_Promo_Code_11]
     , myTarget.[C_Caps_Canopy_Data1] = mySource.[C_Caps_Canopy_Data1]
     , myTarget.[C_Mys_Canopy_Data1] = mySource.[C_Mys_Canopy_Data1]
     , myTarget.[C_MSE_Canopy_Data1] = mySource.[C_MSE_Canopy_Data1]
     , myTarget.[C_Caps_Balance_Due1] = mySource.[C_Caps_Balance_Due1]
     , myTarget.[C_Caps_Decline_Amount_Due1] = mySource.[C_Caps_Decline_Amount_Due1]
     , myTarget.[C_Wiz_Decline_Amount_Due1] = mySource.[C_Wiz_Decline_Amount_Due1]
     , myTarget.[C_Mys_Balance_Due1] = mySource.[C_Mys_Balance_Due1]
     , myTarget.[C_Mys_Decline_Amount_Due1] = mySource.[C_Mys_Decline_Amount_Due1]
     , myTarget.[C_MSE_Balance_Due1] = mySource.[C_MSE_Balance_Due1]
     , myTarget.[C_MSE_Decline_Amount_Due1] = mySource.[C_MSE_Decline_Amount_Due1]
     , myTarget.[C_Caps_Number_of_Group_Seats1] = mySource.[C_Caps_Number_of_Group_Seats1]
     , myTarget.[C_Wiz_Number_of_Group_Seats1] = mySource.[C_Wiz_Number_of_Group_Seats1]
     , myTarget.[C_Mys_Number_of_Group_Seats1] = mySource.[C_Mys_Number_of_Group_Seats1]
     , myTarget.[C_MSE_Number_of_Group_Seats1] = mySource.[C_MSE_Number_of_Group_Seats1]
     , myTarget.[C_Caps_Number_of_Group_Games1] = mySource.[C_Caps_Number_of_Group_Games1]
     , myTarget.[C_Wiz_Number_of_Group_Games1] = mySource.[C_Wiz_Number_of_Group_Games1]
     , myTarget.[C_Mys_Number_of_Group_Games1] = mySource.[C_Mys_Number_of_Group_Games1]
     , myTarget.[C_MSE_Number_of_Group_Games1] = mySource.[C_MSE_Number_of_Group_Games1]
     , myTarget.[C_Caps_Focus_Group_Time1] = mySource.[C_Caps_Focus_Group_Time1]
     , myTarget.[C_Wiz_Focus_Group_Time1] = mySource.[C_Wiz_Focus_Group_Time1]
     , myTarget.[C_Section1] = mySource.[C_Section1]
     , myTarget.[C_Row1] = mySource.[C_Row1]
     , myTarget.[C_Caps___Number_Attending1] = mySource.[C_Caps___Number_Attending1]
     , myTarget.[C_Child_3_Birthday1] = mySource.[C_Child_3_Birthday1]
     , myTarget.[C_Child_4_Birthday1] = mySource.[C_Child_4_Birthday1]
     , myTarget.[C_Child_5_Birthday1] = mySource.[C_Child_5_Birthday1]
     , myTarget.[C_Caps_GS_Rep_Email1] = mySource.[C_Caps_GS_Rep_Email1]
     , myTarget.[C_Caps_GS_Rep_First_Name1] = mySource.[C_Caps_GS_Rep_First_Name1]
     , myTarget.[C_Caps_GS_Rep_Last_Name1] = mySource.[C_Caps_GS_Rep_Last_Name1]
     , myTarget.[C_Caps_GS_Rep_Full_Name1] = mySource.[C_Caps_GS_Rep_Full_Name1]
     , myTarget.[C_Caps_GS_Rep_Phone1] = mySource.[C_Caps_GS_Rep_Phone1]
     , myTarget.[C_Caps_GS_Rep_Title1] = mySource.[C_Caps_GS_Rep_Title1]
     , myTarget.[C_Wiz_GS_Rep_Email1] = mySource.[C_Wiz_GS_Rep_Email1]
     , myTarget.[C_Wiz_GS_Rep_First_Name1] = mySource.[C_Wiz_GS_Rep_First_Name1]
     , myTarget.[C_Wiz_GS_Rep_Last_Name1] = mySource.[C_Wiz_GS_Rep_Last_Name1]
     , myTarget.[C_Wiz_GS_Rep_Full_Name1] = mySource.[C_Wiz_GS_Rep_Full_Name1]
     , myTarget.[C_Wiz_GS_Rep_Phone1] = mySource.[C_Wiz_GS_Rep_Phone1]
     , myTarget.[C_Wiz_GS_Rep_Title1] = mySource.[C_Wiz_GS_Rep_Title1]
     , myTarget.[C_Mys_GS_Rep_Email1] = mySource.[C_Mys_GS_Rep_Email1]
     , myTarget.[C_Mys_GS_Rep_First_Name1] = mySource.[C_Mys_GS_Rep_First_Name1]
     , myTarget.[C_Mys_GS_Rep_Last_name1] = mySource.[C_Mys_GS_Rep_Last_name1]
     , myTarget.[C_Mys_GS_Rep_Full_Name1] = mySource.[C_Mys_GS_Rep_Full_Name1]
     , myTarget.[C_Mys_GS_Rep_Phone1] = mySource.[C_Mys_GS_Rep_Phone1]
     , myTarget.[C_Mys_GS_Rep_Title1] = mySource.[C_Mys_GS_Rep_Title1]
     , myTarget.[C_MSE_Rewards_Type1] = mySource.[C_MSE_Rewards_Type1]
     , myTarget.[C_Wiz_Loyalty_Level1] = mySource.[C_Wiz_Loyalty_Level1]
     , myTarget.[C_Package_Tracking_Number1] = mySource.[C_Package_Tracking_Number1]
     , myTarget.[C_MSE_RepTM_Link_11] = mySource.[C_MSE_RepTM_Link_11]
     , myTarget.[C_Gift_Tracking__11] = mySource.[C_Gift_Tracking__11]
     , myTarget.[C_MSE_Focus_Group_Time1] = mySource.[C_MSE_Focus_Group_Time1]
     , myTarget.[C_AB_Randomized1] = mySource.[C_AB_Randomized1]
     , myTarget.[C_Automation_Yes1_No01] = mySource.[C_Automation_Yes1_No01]
     , myTarget.[C_LinkedIn_Profile1] = mySource.[C_LinkedIn_Profile1]
     , myTarget.[C_Facebook_Profile1] = mySource.[C_Facebook_Profile1]
     , myTarget.[C_Ticket_Type1] = mySource.[C_Ticket_Type1]
     , myTarget.[C_MSE_Renewal_Status1] = mySource.[C_MSE_Renewal_Status1]
     , myTarget.[C_AFL___Sales_Rep_Full_Name1] = mySource.[C_AFL___Sales_Rep_Full_Name1]
     , myTarget.[C_AFL___Sales_Rep_Email1] = mySource.[C_AFL___Sales_Rep_Email1]
     , myTarget.[C_AFL___Sales_Rep_First_Name1] = mySource.[C_AFL___Sales_Rep_First_Name1]
     , myTarget.[C_AFL___Sales_Rep_Last_Name1] = mySource.[C_AFL___Sales_Rep_Last_Name1]
     , myTarget.[C_AFL___Sales_Rep_Phone1] = mySource.[C_AFL___Sales_Rep_Phone1]
     , myTarget.[C_AFL___Sales_Rep_Title1] = mySource.[C_AFL___Sales_Rep_Title1]
     , myTarget.[C_Seat_Number1] = mySource.[C_Seat_Number1]
     , myTarget.[C_MSE_Team1] = mySource.[C_MSE_Team1]
 FROM ods.Eloqua_Contact as myTarget
 JOIN #SrcData as mySource    
	ON myTarget.ID = mySource.ID
	AND myTarget.ETL_DeltaHashKey <> mySource.ETL_DeltaHashKey;


INSERT ods.Eloqua_Contact
     ([ETL_CreatedDate]
     ,[ETL_UpdatedDate]
     ,[ETL_IsDeleted]
     ,[ETL_DeletedDate]
     ,[ETL_DeltaHashKey]
     ,[ID]
     ,[Name]
     ,[AccountName]
     ,[BouncebackDate]
     ,[IsBounceback]
     ,[IsSubscribed]
     ,[PostalCode]
     ,[Province]
     ,[SubscriptionDate]
     ,[UnsubscriptionDate]
     ,[CreatedAt]
     ,[CreatedBy]
     ,[AccessedAt]
     ,[CurrentStatus]
     ,[Depth]
     ,[UpdatedAt]
     ,[UpdatedBy]
     ,[EmailAddress]
     ,[FirstName]
     ,[LastName]
     ,[Company]
     ,[Address1]
     ,[Address2]
     ,[Address3]
     ,[City]
     ,[Country]
     ,[MobilePhone]
     ,[BusinessPhone]
     ,[Fax]
     ,[Title]
     ,[SalesPerson]
     ,[C_State_Prov]
     ,[C_Zip_Postal]
     ,[C_Salutation]
     ,[C_Account]
     ,[C_SFDCContactID]
     ,[C_SFDCLeadID]
     ,[C_Website]
     ,[C_DateCreated]
     ,[C_DateModified]
     ,[ContactIDExt]
     ,[C_SFDCAccountID]
     ,[C_LastModifiedByExtIntegrateSystem]
     ,[C_SFDCLastCampaignID]
     ,[C_SFDCLastCampaignStatus]
     ,[C_Last_Lead_Rating1]
     ,[C_Last_Lead_Score1]
     ,[C_Lead_Score___Historical_All_Time1]
     ,[C_Lead_Rating___Historical_All_Time__HAT_1]
     ,[C_Company_Revenue1]
     ,[C_SFDC_EmailOptOut1]
     ,[C_Lead_Source___Most_Recent1]
     ,[C_Lead_Source___Original1]
     ,[C_Industry1]
     ,[C_Lead_Status1]
     ,[C_Job_Role1]
     ,[C_Last_Website_Visit_Date_and_Time1]
     ,[C_LS___High_Value_Website_Content1]
     ,[C_DUNS_Number]
     ,[C_Doing_Business_As]
     ,[C_CEO_Name]
     ,[C_Industry]
     ,[C_SIC_Code]
     ,[C_Established_In]
     ,[C_Annual_Sales_Indicator]
     ,[C_Annual_Sales]
     ,[C_Total_Employees]
     ,[C_Total_Employees_Indicator]
     ,[C_Lead_Score_Date___Most_Recent1]
     ,[C_Integrated_Marketing_and_Sales_Funnel_Stage]
     ,[C_Product_Solution_of_Interest1]
     ,[C_Region1]
     ,[C_elqPURLName1]
     ,[C_Most_Recent_Form_Submitted1]
     ,[C_Household_Income1]
     ,[C___of_Times_Downloaded_High_Valued_Content__]
     ,[C___of_Times_Downloaded_High_Valued_Content__3]
     ,[C___of_Times_Downloaded_High_Valued_Content__4]
     ,[C_Lead_Rating___Combined1]
     ,[C_Purchase_History___Most_Recent1]
     ,[C___Times_Viewed_High_Value_Content___ALL1]
     ,[C_Total_Visits1]
     ,[C_Daytime_Phone1]
     ,[C_Evening_Phone1]
     ,[C_Name_Last1]
     ,[C_Acct_Type_Desc1]
     ,[C_Email_Opt_In1]
     ,[C_Birthdate1]
     ,[C_Favorite_Player1]
     ,[C_elqPURLName3]
     ,[C_EmailAddressDomain]
     ,[C_FirstAndLastName]
     ,[C_Best_Time_to_Conact1]
     ,[C_Mobile_Opt_In1]
     ,[C_Guest_Services_Rep1]
     ,[C_Phone1]
     ,[C_Season1]
     ,[C_Gender1]
     ,[C_Renewal_Memo_Code1]
     ,[C_Payment_Memo_Code1]
     ,[C_Number_of_Seats1]
     ,[C_Select_a_seat_2011_12_Yes_No1]
     ,[C_2011_12_Sales_Pack_Interest1]
     ,[C_Contact_Preference_for_Sales1]
     ,[C_Executive_Suite_Interest1]
     ,[C_Group_Size_Interest1]
     ,[C_Attention_Name1]
     ,[C_Alt_Address_11]
     ,[C_Alt_Address_21]
     ,[C_Alt_City1]
     ,[C_Alt_Zip_Code1]
     ,[C_Alt_State1]
     ,[C_Alt_Company1]
     ,[C_SFDCLastCampaignName]
     ,[C_SFDC_Lead_Rating1]
     ,[C_Caps_STH_Loyalty1]
     ,[C_Guest_Services_Reps_II1]
     ,[C_elqPURLName4]
     ,[C_elqPURLName5]
     ,[C_elqPURLName6]
     ,[C_SFDC_Interests1]
     ,[C_Suite_Facility1]
     ,[C_Suite__1]
     ,[C_Suite_Seats1]
     ,[C_Lead_Score___Last_High_Touch_Event_Date1]
     ,[C_Last_Single_Game_Ticket_Purchase_Date1]
     ,[C_B2C___Lead_Rating___Combined1]
     ,[C_B2C___Lead_Rating___Explicit1]
     ,[C_B2C___Lead_Score___Explicit1]
     ,[C_B2C___Lead_Rating___Implicit1]
     ,[C_B2C___Lead_Score___High_Value_Website_Conte]
     ,[C_B2C___Lead_Score___Implicit1]
     ,[C_B2C___Lead_Score_Date___Most_Recent1]
     ,[C_Number_of_Employees1]
     ,[C_Past_Purchases__Suite___Sponsorships_1]
     ,[C_Zip_Code__Georgraphic_Area_1]
     ,[C_Previous_Purchase1]
     ,[C_Discretionary_Income1]
     ,[C_Wizards_Account_ID1]
     ,[C_Mystics_Account_ID1]
     ,[C_Interests1]
     ,[C_Annual_Revenue1]
     ,[C_Turnkey_Rating___Score1]
     ,[C_Child_11]
     ,[C_Child_21]
     ,[C_Child_31]
     ,[C_Season_Ticket_Holder1]
     ,[C_Wiz___Balance_Due1]
     ,[C_Wiz___Guest_Services_Reps1]
     ,[C_Child_41]
     ,[C_Child_51]
     ,[C_Child_2_Birthday1]
     ,[C_Child_1_Birthday1]
     ,[C_Caps_Kids_Club1]
     ,[C_Caps_Kids_Club_Referral_Email1]
     ,[C_Birthdate_C1]
     ,[C_Birthdate_W1]
     ,[C_Birthdate_M1]
     ,[C_Type_of_Mobile_Phone1]
     ,[C_Caps___12_13_Par__STH__Dep__Premium_Renewal]
     ,[C_Rep_Phone1]
     ,[C_Rep_Email1]
     ,[C_Package_Interest1]
     ,[C_Question_Comments1]
     ,[C_Premium_Package_Rep1]
     ,[C_Caps_Non_Renewed_Rep1]
     ,[C_Referred_by_First_Name1]
     ,[C_Referred_by_Last_Name1]
     ,[C_Territory]
     ,[C_SFDC_Ticket___Rep_Name1]
     ,[C_SFDC_Ticket___Price_Code1]
     ,[C_SFDC_Ticket___Event_Name1]
     ,[C_SFDC_Ticket___Purchase_Qty1]
     ,[C_SFDC_Ticket___Purchase_Price1]
     ,[C_SFDC_Ticket___Archtics_ID1]
     ,[C_SFDC_Ticket___Purchase_Date1]
     ,[C_SFDC_Ticket___First_Name1]
     ,[C_Caps___Holiday_PURL1]
     ,[C_Wiz___Holiday_E_Card_Purl1]
     ,[C_Wiz___Holiday_Pack_Game_11]
     ,[C_Wiz___Holiday_Pack_Game_21]
     ,[C_Lead_Score]
     ,[C_ElqPURLName]
     ,[C_Suites___Rep_Name1]
     ,[C_Caps___STH_Presale_Time1]
     ,[C_Caps_TA_and_IC_Opt_Ins1]
     ,[C_Twitter_Handle1]
     ,[C_Sales_Rep_First_Name1]
     ,[C_Full_Name1]
     ,[C_MSE_Account_ID1]
     ,[C_Last_4_CC_Digits1]
     ,[C_CC_Type1]
     ,[C_CC_Expiration1]
     ,[C_Rep_Title1]
     ,[C_Decline_Amount_Due1]
     ,[C_Wiz___Canopy_Data1]
     ,[C_MSE_Rewards_Amount1]
     ,[C_Wiz___PG_Season_Name1]
     ,[C_Wiz___PG_Event_Opponent1]
     ,[C_Wiz___PG_Event_Date1]
     ,[C_MSE___Current_Rewards_Points1]
     ,[C_MSE___Accrued_Rewards_Points1]
     ,[C_MSE_____of_Rewards_Logins1]
     ,[C_MSE___Last_Rewards_Login1]
     ,[C_MSE___Spent_Rewards_Points1]
     ,[C_Wiz___STH_Presale_Timeslot1]
     ,[C_MD5HashedEmailAddress]
     ,[C_SHA256HashedEmailAddress]
     ,[C_MD5HashedBusPhone]
     ,[C_SHA256HashedBusPhone]
     ,[C_MD5HashedMobilePhone]
     ,[C_SHA256HashedMobilePhone]
     ,[C_Wiz___Promo_Code1]
     ,[C_Caps_201516_Renewal_PURL1]
     ,[C_Caps___Kids_Club_Expire_Date1]
     ,[C_Caps___SAS_Timeslot1]
     ,[C_STH_Since_Date__Caps1]
     ,[C_Caps_Sales_Rep_Full_Name1]
     ,[C_Caps_Sales_Rep_First_Name1]
     ,[C_Caps_Sales_Rep_Last_Name1]
     ,[C_Caps_Sales_Rep_Email1]
     ,[C_Caps_Sales_Rep_Phone1]
     ,[C_Caps_Sales_Rep_Title1]
     ,[C_Wiz_Sales_Rep_Full_Name1]
     ,[C_Wiz_Sales_Rep_First_Name1]
     ,[C_Wiz_Sales_Rep_Last_Name1]
     ,[C_Wiz_Sales_Rep_Email1]
     ,[C_Wiz_Sales_Rep_Phone1]
     ,[C_Wiz_Sales_Rep_Title1]
     ,[C_Mys_Sales_Rep_Full_Name1]
     ,[C_Mys_Sales_Rep_First_Name1]
     ,[C_Mys_Sales_Rep_Last_Name1]
     ,[C_Mys_Sales_Rep_Email1]
     ,[C_Mys_Sales_Rep_Phone1]
     ,[C_Mys_Sales_Rep_Title1]
     ,[C_MSE_Sales_Rep_Full_Name1]
     ,[C_MSE_Sales_Rep_First_Name1]
     ,[C_MSE_Sales_Rep_Last_Name1]
     ,[C_MSE_Sales_Rep_Email1]
     ,[C_MSE_Sales_Rep_Phone1]
     ,[C_MSE_Sales_Rep_Title1]
     ,[C_Alt_Country1]
     ,[C_Caps_RepTM_Link_11]
     ,[C_Wiz_RepTM_Link_11]
     ,[C_Mys_RepTM_Link_11]
     ,[C_Caps_PURL_11]
     ,[C_Wiz_PURL_11]
     ,[C_Mys_PURL_11]
     ,[C_Mys_STH_Presale_Timeslot1]
     ,[C_MSE_STH_Presale_Timeslot1]
     ,[C_Caps_Promo_Code_11]
     ,[C_Mys_Promo_Code_11]
     ,[C_Caps_Canopy_Data1]
     ,[C_Mys_Canopy_Data1]
     ,[C_MSE_Canopy_Data1]
     ,[C_Caps_Balance_Due1]
     ,[C_Caps_Decline_Amount_Due1]
     ,[C_Wiz_Decline_Amount_Due1]
     ,[C_Mys_Balance_Due1]
     ,[C_Mys_Decline_Amount_Due1]
     ,[C_MSE_Balance_Due1]
     ,[C_MSE_Decline_Amount_Due1]
     ,[C_Caps_Number_of_Group_Seats1]
     ,[C_Wiz_Number_of_Group_Seats1]
     ,[C_Mys_Number_of_Group_Seats1]
     ,[C_MSE_Number_of_Group_Seats1]
     ,[C_Caps_Number_of_Group_Games1]
     ,[C_Wiz_Number_of_Group_Games1]
     ,[C_Mys_Number_of_Group_Games1]
     ,[C_MSE_Number_of_Group_Games1]
     ,[C_Caps_Focus_Group_Time1]
     ,[C_Wiz_Focus_Group_Time1]
     ,[C_Section1]
     ,[C_Row1]
     ,[C_Caps___Number_Attending1]
     ,[C_Child_3_Birthday1]
     ,[C_Child_4_Birthday1]
     ,[C_Child_5_Birthday1]
     ,[C_Caps_GS_Rep_Email1]
     ,[C_Caps_GS_Rep_First_Name1]
     ,[C_Caps_GS_Rep_Last_Name1]
     ,[C_Caps_GS_Rep_Full_Name1]
     ,[C_Caps_GS_Rep_Phone1]
     ,[C_Caps_GS_Rep_Title1]
     ,[C_Wiz_GS_Rep_Email1]
     ,[C_Wiz_GS_Rep_First_Name1]
     ,[C_Wiz_GS_Rep_Last_Name1]
     ,[C_Wiz_GS_Rep_Full_Name1]
     ,[C_Wiz_GS_Rep_Phone1]
     ,[C_Wiz_GS_Rep_Title1]
     ,[C_Mys_GS_Rep_Email1]
     ,[C_Mys_GS_Rep_First_Name1]
     ,[C_Mys_GS_Rep_Last_name1]
     ,[C_Mys_GS_Rep_Full_Name1]
     ,[C_Mys_GS_Rep_Phone1]
     ,[C_Mys_GS_Rep_Title1]
     ,[C_MSE_Rewards_Type1]
     ,[C_Wiz_Loyalty_Level1]
     ,[C_Package_Tracking_Number1]
     ,[C_MSE_RepTM_Link_11]
     ,[C_Gift_Tracking__11]
     ,[C_MSE_Focus_Group_Time1]
     ,[C_AB_Randomized1]
     ,[C_Automation_Yes1_No01]
     ,[C_LinkedIn_Profile1]
     ,[C_Facebook_Profile1]
     ,[C_Ticket_Type1]
     ,[C_MSE_Renewal_Status1]
     ,[C_AFL___Sales_Rep_Full_Name1]
     ,[C_AFL___Sales_Rep_Email1]
     ,[C_AFL___Sales_Rep_First_Name1]
     ,[C_AFL___Sales_Rep_Last_Name1]
     ,[C_AFL___Sales_Rep_Phone1]
     ,[C_AFL___Sales_Rep_Title1]
     ,[C_Seat_Number1]
     ,[C_MSE_Team1]
     )
SELECT
	  @RunTime	--ETL_CreatedDate
     ,@RunTime	--ETL_UpdateddDate
     ,0			--ETL_IsDeleted
     ,NULL		--ETL_DeletedDate
     ,mySource.[ETL_DeltaHashKey]
     ,mySource.[ID]
     ,mySource.[Name]
     ,mySource.[AccountName]
     ,mySource.[BouncebackDate]
     ,mySource.[IsBounceback]
     ,mySource.[IsSubscribed]
     ,mySource.[PostalCode]
     ,mySource.[Province]
     ,mySource.[SubscriptionDate]
     ,mySource.[UnsubscriptionDate]
     ,mySource.[CreatedAt]
     ,mySource.[CreatedBy]
     ,mySource.[AccessedAt]
     ,mySource.[CurrentStatus]
     ,mySource.[Depth]
     ,mySource.[UpdatedAt]
     ,mySource.[UpdatedBy]
     ,mySource.[EmailAddress]
     ,mySource.[FirstName]
     ,mySource.[LastName]
     ,mySource.[Company]
     ,mySource.[Address1]
     ,mySource.[Address2]
     ,mySource.[Address3]
     ,mySource.[City]
     ,mySource.[Country]
     ,mySource.[MobilePhone]
     ,mySource.[BusinessPhone]
     ,mySource.[Fax]
     ,mySource.[Title]
     ,mySource.[SalesPerson]
     ,mySource.[C_State_Prov]
     ,mySource.[C_Zip_Postal]
     ,mySource.[C_Salutation]
     ,mySource.[C_Account]
     ,mySource.[C_SFDCContactID]
     ,mySource.[C_SFDCLeadID]
     ,mySource.[C_Website]
     ,mySource.[C_DateCreated]
     ,mySource.[C_DateModified]
     ,mySource.[ContactIDExt]
     ,mySource.[C_SFDCAccountID]
     ,mySource.[C_LastModifiedByExtIntegrateSystem]
     ,mySource.[C_SFDCLastCampaignID]
     ,mySource.[C_SFDCLastCampaignStatus]
     ,mySource.[C_Last_Lead_Rating1]
     ,mySource.[C_Last_Lead_Score1]
     ,mySource.[C_Lead_Score___Historical_All_Time1]
     ,mySource.[C_Lead_Rating___Historical_All_Time__HAT_1]
     ,mySource.[C_Company_Revenue1]
     ,mySource.[C_SFDC_EmailOptOut1]
     ,mySource.[C_Lead_Source___Most_Recent1]
     ,mySource.[C_Lead_Source___Original1]
     ,mySource.[C_Industry1]
     ,mySource.[C_Lead_Status1]
     ,mySource.[C_Job_Role1]
     ,mySource.[C_Last_Website_Visit_Date_and_Time1]
     ,mySource.[C_LS___High_Value_Website_Content1]
     ,mySource.[C_DUNS_Number]
     ,mySource.[C_Doing_Business_As]
     ,mySource.[C_CEO_Name]
     ,mySource.[C_Industry]
     ,mySource.[C_SIC_Code]
     ,mySource.[C_Established_In]
     ,mySource.[C_Annual_Sales_Indicator]
     ,mySource.[C_Annual_Sales]
     ,mySource.[C_Total_Employees]
     ,mySource.[C_Total_Employees_Indicator]
     ,mySource.[C_Lead_Score_Date___Most_Recent1]
     ,mySource.[C_Integrated_Marketing_and_Sales_Funnel_Stage]
     ,mySource.[C_Product_Solution_of_Interest1]
     ,mySource.[C_Region1]
     ,mySource.[C_elqPURLName1]
     ,mySource.[C_Most_Recent_Form_Submitted1]
     ,mySource.[C_Household_Income1]
     ,mySource.[C___of_Times_Downloaded_High_Valued_Content__]
     ,mySource.[C___of_Times_Downloaded_High_Valued_Content__3]
     ,mySource.[C___of_Times_Downloaded_High_Valued_Content__4]
     ,mySource.[C_Lead_Rating___Combined1]
     ,mySource.[C_Purchase_History___Most_Recent1]
     ,mySource.[C___Times_Viewed_High_Value_Content___ALL1]
     ,mySource.[C_Total_Visits1]
     ,mySource.[C_Daytime_Phone1]
     ,mySource.[C_Evening_Phone1]
     ,mySource.[C_Name_Last1]
     ,mySource.[C_Acct_Type_Desc1]
     ,mySource.[C_Email_Opt_In1]
     ,mySource.[C_Birthdate1]
     ,mySource.[C_Favorite_Player1]
     ,mySource.[C_elqPURLName3]
     ,mySource.[C_EmailAddressDomain]
     ,mySource.[C_FirstAndLastName]
     ,mySource.[C_Best_Time_to_Conact1]
     ,mySource.[C_Mobile_Opt_In1]
     ,mySource.[C_Guest_Services_Rep1]
     ,mySource.[C_Phone1]
     ,mySource.[C_Season1]
     ,mySource.[C_Gender1]
     ,mySource.[C_Renewal_Memo_Code1]
     ,mySource.[C_Payment_Memo_Code1]
     ,mySource.[C_Number_of_Seats1]
     ,mySource.[C_Select_a_seat_2011_12_Yes_No1]
     ,mySource.[C_2011_12_Sales_Pack_Interest1]
     ,mySource.[C_Contact_Preference_for_Sales1]
     ,mySource.[C_Executive_Suite_Interest1]
     ,mySource.[C_Group_Size_Interest1]
     ,mySource.[C_Attention_Name1]
     ,mySource.[C_Alt_Address_11]
     ,mySource.[C_Alt_Address_21]
     ,mySource.[C_Alt_City1]
     ,mySource.[C_Alt_Zip_Code1]
     ,mySource.[C_Alt_State1]
     ,mySource.[C_Alt_Company1]
     ,mySource.[C_SFDCLastCampaignName]
     ,mySource.[C_SFDC_Lead_Rating1]
     ,mySource.[C_Caps_STH_Loyalty1]
     ,mySource.[C_Guest_Services_Reps_II1]
     ,mySource.[C_elqPURLName4]
     ,mySource.[C_elqPURLName5]
     ,mySource.[C_elqPURLName6]
     ,mySource.[C_SFDC_Interests1]
     ,mySource.[C_Suite_Facility1]
     ,mySource.[C_Suite__1]
     ,mySource.[C_Suite_Seats1]
     ,mySource.[C_Lead_Score___Last_High_Touch_Event_Date1]
     ,mySource.[C_Last_Single_Game_Ticket_Purchase_Date1]
     ,mySource.[C_B2C___Lead_Rating___Combined1]
     ,mySource.[C_B2C___Lead_Rating___Explicit1]
     ,mySource.[C_B2C___Lead_Score___Explicit1]
     ,mySource.[C_B2C___Lead_Rating___Implicit1]
     ,mySource.[C_B2C___Lead_Score___High_Value_Website_Conte]
     ,mySource.[C_B2C___Lead_Score___Implicit1]
     ,mySource.[C_B2C___Lead_Score_Date___Most_Recent1]
     ,mySource.[C_Number_of_Employees1]
     ,mySource.[C_Past_Purchases__Suite___Sponsorships_1]
     ,mySource.[C_Zip_Code__Georgraphic_Area_1]
     ,mySource.[C_Previous_Purchase1]
     ,mySource.[C_Discretionary_Income1]
     ,mySource.[C_Wizards_Account_ID1]
     ,mySource.[C_Mystics_Account_ID1]
     ,mySource.[C_Interests1]
     ,mySource.[C_Annual_Revenue1]
     ,mySource.[C_Turnkey_Rating___Score1]
     ,mySource.[C_Child_11]
     ,mySource.[C_Child_21]
     ,mySource.[C_Child_31]
     ,mySource.[C_Season_Ticket_Holder1]
     ,mySource.[C_Wiz___Balance_Due1]
     ,mySource.[C_Wiz___Guest_Services_Reps1]
     ,mySource.[C_Child_41]
     ,mySource.[C_Child_51]
     ,mySource.[C_Child_2_Birthday1]
     ,mySource.[C_Child_1_Birthday1]
     ,mySource.[C_Caps_Kids_Club1]
     ,mySource.[C_Caps_Kids_Club_Referral_Email1]
     ,mySource.[C_Birthdate_C1]
     ,mySource.[C_Birthdate_W1]
     ,mySource.[C_Birthdate_M1]
     ,mySource.[C_Type_of_Mobile_Phone1]
     ,mySource.[C_Caps___12_13_Par__STH__Dep__Premium_Renewal]
     ,mySource.[C_Rep_Phone1]
     ,mySource.[C_Rep_Email1]
     ,mySource.[C_Package_Interest1]
     ,mySource.[C_Question_Comments1]
     ,mySource.[C_Premium_Package_Rep1]
     ,mySource.[C_Caps_Non_Renewed_Rep1]
     ,mySource.[C_Referred_by_First_Name1]
     ,mySource.[C_Referred_by_Last_Name1]
     ,mySource.[C_Territory]
     ,mySource.[C_SFDC_Ticket___Rep_Name1]
     ,mySource.[C_SFDC_Ticket___Price_Code1]
     ,mySource.[C_SFDC_Ticket___Event_Name1]
     ,mySource.[C_SFDC_Ticket___Purchase_Qty1]
     ,mySource.[C_SFDC_Ticket___Purchase_Price1]
     ,mySource.[C_SFDC_Ticket___Archtics_ID1]
     ,mySource.[C_SFDC_Ticket___Purchase_Date1]
     ,mySource.[C_SFDC_Ticket___First_Name1]
     ,mySource.[C_Caps___Holiday_PURL1]
     ,mySource.[C_Wiz___Holiday_E_Card_Purl1]
     ,mySource.[C_Wiz___Holiday_Pack_Game_11]
     ,mySource.[C_Wiz___Holiday_Pack_Game_21]
     ,mySource.[C_Lead_Score]
     ,mySource.[C_ElqPURLName]
     ,mySource.[C_Suites___Rep_Name1]
     ,mySource.[C_Caps___STH_Presale_Time1]
     ,mySource.[C_Caps_TA_and_IC_Opt_Ins1]
     ,mySource.[C_Twitter_Handle1]
     ,mySource.[C_Sales_Rep_First_Name1]
     ,mySource.[C_Full_Name1]
     ,mySource.[C_MSE_Account_ID1]
     ,mySource.[C_Last_4_CC_Digits1]
     ,mySource.[C_CC_Type1]
     ,mySource.[C_CC_Expiration1]
     ,mySource.[C_Rep_Title1]
     ,mySource.[C_Decline_Amount_Due1]
     ,mySource.[C_Wiz___Canopy_Data1]
     ,mySource.[C_MSE_Rewards_Amount1]
     ,mySource.[C_Wiz___PG_Season_Name1]
     ,mySource.[C_Wiz___PG_Event_Opponent1]
     ,mySource.[C_Wiz___PG_Event_Date1]
     ,mySource.[C_MSE___Current_Rewards_Points1]
     ,mySource.[C_MSE___Accrued_Rewards_Points1]
     ,mySource.[C_MSE_____of_Rewards_Logins1]
     ,mySource.[C_MSE___Last_Rewards_Login1]
     ,mySource.[C_MSE___Spent_Rewards_Points1]
     ,mySource.[C_Wiz___STH_Presale_Timeslot1]
     ,mySource.[C_MD5HashedEmailAddress]
     ,mySource.[C_SHA256HashedEmailAddress]
     ,mySource.[C_MD5HashedBusPhone]
     ,mySource.[C_SHA256HashedBusPhone]
     ,mySource.[C_MD5HashedMobilePhone]
     ,mySource.[C_SHA256HashedMobilePhone]
     ,mySource.[C_Wiz___Promo_Code1]
     ,mySource.[C_Caps_201516_Renewal_PURL1]
     ,mySource.[C_Caps___Kids_Club_Expire_Date1]
     ,mySource.[C_Caps___SAS_Timeslot1]
     ,mySource.[C_STH_Since_Date__Caps1]
     ,mySource.[C_Caps_Sales_Rep_Full_Name1]
     ,mySource.[C_Caps_Sales_Rep_First_Name1]
     ,mySource.[C_Caps_Sales_Rep_Last_Name1]
     ,mySource.[C_Caps_Sales_Rep_Email1]
     ,mySource.[C_Caps_Sales_Rep_Phone1]
     ,mySource.[C_Caps_Sales_Rep_Title1]
     ,mySource.[C_Wiz_Sales_Rep_Full_Name1]
     ,mySource.[C_Wiz_Sales_Rep_First_Name1]
     ,mySource.[C_Wiz_Sales_Rep_Last_Name1]
     ,mySource.[C_Wiz_Sales_Rep_Email1]
     ,mySource.[C_Wiz_Sales_Rep_Phone1]
     ,mySource.[C_Wiz_Sales_Rep_Title1]
     ,mySource.[C_Mys_Sales_Rep_Full_Name1]
     ,mySource.[C_Mys_Sales_Rep_First_Name1]
     ,mySource.[C_Mys_Sales_Rep_Last_Name1]
     ,mySource.[C_Mys_Sales_Rep_Email1]
     ,mySource.[C_Mys_Sales_Rep_Phone1]
     ,mySource.[C_Mys_Sales_Rep_Title1]
     ,mySource.[C_MSE_Sales_Rep_Full_Name1]
     ,mySource.[C_MSE_Sales_Rep_First_Name1]
     ,mySource.[C_MSE_Sales_Rep_Last_Name1]
     ,mySource.[C_MSE_Sales_Rep_Email1]
     ,mySource.[C_MSE_Sales_Rep_Phone1]
     ,mySource.[C_MSE_Sales_Rep_Title1]
     ,mySource.[C_Alt_Country1]
     ,mySource.[C_Caps_RepTM_Link_11]
     ,mySource.[C_Wiz_RepTM_Link_11]
     ,mySource.[C_Mys_RepTM_Link_11]
     ,mySource.[C_Caps_PURL_11]
     ,mySource.[C_Wiz_PURL_11]
     ,mySource.[C_Mys_PURL_11]
     ,mySource.[C_Mys_STH_Presale_Timeslot1]
     ,mySource.[C_MSE_STH_Presale_Timeslot1]
     ,mySource.[C_Caps_Promo_Code_11]
     ,mySource.[C_Mys_Promo_Code_11]
     ,mySource.[C_Caps_Canopy_Data1]
     ,mySource.[C_Mys_Canopy_Data1]
     ,mySource.[C_MSE_Canopy_Data1]
     ,mySource.[C_Caps_Balance_Due1]
     ,mySource.[C_Caps_Decline_Amount_Due1]
     ,mySource.[C_Wiz_Decline_Amount_Due1]
     ,mySource.[C_Mys_Balance_Due1]
     ,mySource.[C_Mys_Decline_Amount_Due1]
     ,mySource.[C_MSE_Balance_Due1]
     ,mySource.[C_MSE_Decline_Amount_Due1]
     ,mySource.[C_Caps_Number_of_Group_Seats1]
     ,mySource.[C_Wiz_Number_of_Group_Seats1]
     ,mySource.[C_Mys_Number_of_Group_Seats1]
     ,mySource.[C_MSE_Number_of_Group_Seats1]
     ,mySource.[C_Caps_Number_of_Group_Games1]
     ,mySource.[C_Wiz_Number_of_Group_Games1]
     ,mySource.[C_Mys_Number_of_Group_Games1]
     ,mySource.[C_MSE_Number_of_Group_Games1]
     ,mySource.[C_Caps_Focus_Group_Time1]
     ,mySource.[C_Wiz_Focus_Group_Time1]
     ,mySource.[C_Section1]
     ,mySource.[C_Row1]
     ,mySource.[C_Caps___Number_Attending1]
     ,mySource.[C_Child_3_Birthday1]
     ,mySource.[C_Child_4_Birthday1]
     ,mySource.[C_Child_5_Birthday1]
     ,mySource.[C_Caps_GS_Rep_Email1]
     ,mySource.[C_Caps_GS_Rep_First_Name1]
     ,mySource.[C_Caps_GS_Rep_Last_Name1]
     ,mySource.[C_Caps_GS_Rep_Full_Name1]
     ,mySource.[C_Caps_GS_Rep_Phone1]
     ,mySource.[C_Caps_GS_Rep_Title1]
     ,mySource.[C_Wiz_GS_Rep_Email1]
     ,mySource.[C_Wiz_GS_Rep_First_Name1]
     ,mySource.[C_Wiz_GS_Rep_Last_Name1]
     ,mySource.[C_Wiz_GS_Rep_Full_Name1]
     ,mySource.[C_Wiz_GS_Rep_Phone1]
     ,mySource.[C_Wiz_GS_Rep_Title1]
     ,mySource.[C_Mys_GS_Rep_Email1]
     ,mySource.[C_Mys_GS_Rep_First_Name1]
     ,mySource.[C_Mys_GS_Rep_Last_name1]
     ,mySource.[C_Mys_GS_Rep_Full_Name1]
     ,mySource.[C_Mys_GS_Rep_Phone1]
     ,mySource.[C_Mys_GS_Rep_Title1]
     ,mySource.[C_MSE_Rewards_Type1]
     ,mySource.[C_Wiz_Loyalty_Level1]
     ,mySource.[C_Package_Tracking_Number1]
     ,mySource.[C_MSE_RepTM_Link_11]
     ,mySource.[C_Gift_Tracking__11]
     ,mySource.[C_MSE_Focus_Group_Time1]
     ,mySource.[C_AB_Randomized1]
     ,mySource.[C_Automation_Yes1_No01]
     ,mySource.[C_LinkedIn_Profile1]
     ,mySource.[C_Facebook_Profile1]
     ,mySource.[C_Ticket_Type1]
     ,mySource.[C_MSE_Renewal_Status1]
     ,mySource.[C_AFL___Sales_Rep_Full_Name1]
     ,mySource.[C_AFL___Sales_Rep_Email1]
     ,mySource.[C_AFL___Sales_Rep_First_Name1]
     ,mySource.[C_AFL___Sales_Rep_Last_Name1]
     ,mySource.[C_AFL___Sales_Rep_Phone1]
     ,mySource.[C_AFL___Sales_Rep_Title1]
     ,mySource.[C_Seat_Number1]
     ,mySource.[C_MSE_Team1]
FROM #SrcData as mySource
LEFT JOIN ods.Eloqua_Contact as myTarget
	ON mySource.ID = myTarget.ID
WHERE myTarget.ID IS NULL;


END TRY 
BEGIN CATCH 

	DECLARE @ErrorMessage nvarchar(4000) = ERROR_MESSAGE();
	DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
	DECLARE @ErrorState INT = ERROR_STATE();
			
	PRINT @ErrorMessage;
	RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH


END






GO
