CREATE TABLE [dbo].[Bears_LiveA_Bhvr_20170906]
(
[ult_party_id] [int] NULL,
[acct_id] [varchar] (144) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_source_cd] [varchar] (44) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[la_id] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[behavior_score_05] [smallint] NULL,
[behavior_score_06] [smallint] NULL,
[behavior_score_07] [smallint] NULL,
[behavior_score_09] [smallint] NULL,
[behavior_score_10] [smallint] NULL,
[behavior_score_11] [smallint] NULL,
[behavior_score_12] [smallint] NULL,
[behavior_score_13] [smallint] NULL,
[behavior_score_22] [smallint] NULL,
[behavior_score_23] [smallint] NULL,
[behavior_score_24] [smallint] NULL,
[dim_01_ind] [smallint] NULL,
[dim_02_ind] [smallint] NULL,
[dim_03_ind] [smallint] NULL,
[dim_04_ind] [smallint] NULL,
[dim_05_ind] [smallint] NULL,
[dim_06_ind] [smallint] NULL,
[dim_07_ind] [smallint] NULL,
[dim_08_ind] [smallint] NULL,
[dim_09_ind] [smallint] NULL,
[dim_10_ind] [smallint] NULL,
[dim_11_ind] [smallint] NULL,
[dim_12_ind] [smallint] NULL,
[dim_13_ind] [smallint] NULL,
[dim_14_ind] [smallint] NULL,
[dim_15_ind] [smallint] NULL,
[dim_16_ind] [smallint] NULL,
[dim_17_ind] [smallint] NULL,
[dim_18_ind] [smallint] NULL,
[dim_19_ind] [smallint] NULL,
[dim_20_ind] [smallint] NULL,
[dim_21_ind] [smallint] NULL,
[dim_22_ind] [smallint] NULL,
[dim_23_ind] [smallint] NULL,
[dim_24_ind] [smallint] NULL,
[dim_25_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_26_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_27_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_28_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_29_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_30_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_31_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_32_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_33_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_34_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_35_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_36_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_37_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_38_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_39_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_40_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_41_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_42_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_43_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_44_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_45_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_46_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_47_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_48_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_49_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_50_ind] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
