CREATE TABLE [ods].[Bears_LiveA_Cust_20170906]
(
[ult_party_id] [int] NULL,
[acct_id] [varchar] (126) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_source_cd] [varchar] (38) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[la_id] [varchar] (56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_first_nm] [varchar] (122) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_middle_nm] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_last_nm] [varchar] (87) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_addr_line_1] [varchar] (175) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_addr_line_2] [varchar] (87) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_city_nm] [varchar] (87) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_state_nm] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_postal_cd] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_ctry_nm] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_phn_num_1] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_phn_num_2] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cust_email_addr] [varchar] (164) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[livea_match_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[first_indv_first_nm] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[first_indv_md_nm] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[second_indv_first_nm] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[second_indv_md_nm] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gndr_input_indv_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gndr_1st_indv_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gndr_2nd_indv_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[age_two_yr_incr_input_indv] [smallint] NULL,
[age_two_yr_incr_1st_indv] [smallint] NULL,
[age_two_yr_incr_2nd_indv] [smallint] NULL,
[race_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[adult_hh_num] [smallint] NULL,
[presence_chldn_new_flg] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[marital_status_hh_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hh_male_18_24_ind] [smallint] NULL,
[hh_female_18_24_ind] [smallint] NULL,
[hh_unk_18_24_ind] [smallint] NULL,
[hh_male_25_34_ind] [smallint] NULL,
[hh_female_25_34_ind] [smallint] NULL,
[hh_unk_25_34_ind] [smallint] NULL,
[hh_male_35_44_ind] [smallint] NULL,
[hh_female_35_44_ind] [smallint] NULL,
[hh_unk_35_44_ind] [smallint] NULL,
[hh_male_45_54_ind] [smallint] NULL,
[hh_female_45_54_ind] [smallint] NULL,
[hh_unk_45_54_ind] [smallint] NULL,
[hh_male_55_64_ind] [smallint] NULL,
[hh_female_55_64_ind] [smallint] NULL,
[hh_unk_55_64_ind] [smallint] NULL,
[hh_male_65_74_ind] [smallint] NULL,
[hh_female_65_74_ind] [smallint] NULL,
[hh_unk_65_74_ind] [smallint] NULL,
[hh_male_75_plus_ind] [smallint] NULL,
[hh_female_75_plus_ind] [smallint] NULL,
[hh_unk_75_plus_ind] [smallint] NULL,
[hh_male_00_02_ind] [smallint] NULL,
[hh_female_00_02_ind] [smallint] NULL,
[hh_unk_00_02_ind] [smallint] NULL,
[hh_male_03_05_ind] [smallint] NULL,
[hh_female_03_05_ind] [smallint] NULL,
[hh_unk_03_05_ind] [smallint] NULL,
[hh_male_06_10_ind] [smallint] NULL,
[hh_female_06_10_ind] [smallint] NULL,
[hh_unk_06_10_ind] [smallint] NULL,
[hh_male_11_15_ind] [smallint] NULL,
[hh_female_11_15_ind] [smallint] NULL,
[hh_unk_11_15_ind] [smallint] NULL,
[hh_male_16_17_ind] [smallint] NULL,
[hh_female_16_17_ind] [smallint] NULL,
[hh_unk_16_17_ind] [smallint] NULL,
[len_of_resdnc_cd] [smallint] NULL,
[dwlng_type_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[suprs_mail_dma_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[occpn_input_indv_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[occpn_1st_indv_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[occpn_2nd_indv_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[wrk_wmn_hh_flg] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[income_est_hh_cd] [smallint] NULL,
[est_hh_inc_higher_ranges_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[est_hh_inc_narrow_ranges_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[est_hh_inc_cd_100pct_inc_cd] [smallint] NULL,
[est_hh_inc_cd_100pct_prec_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[net_worth_gold_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[discretionary_income_index_cd] [smallint] NULL,
[financial_pct_score] [smallint] NULL,
[bank_card_hldr_cd] [smallint] NULL,
[gas_dept_retail_card_hldr_cd] [smallint] NULL,
[travel_ent_card_hldr_cd] [smallint] NULL,
[credit_card_unk_type_hld_cd] [smallint] NULL,
[prem_card_hldr_cd] [smallint] NULL,
[upscale_dept_str_card_hldr_cd] [smallint] NULL,
[e3_pmt_visa_ind] [smallint] NULL,
[e3_pmt_mc_ind] [smallint] NULL,
[e3_pmt_amex_ind] [smallint] NULL,
[e3_pmt_disc_ind] [smallint] NULL,
[e3_pmt_other_ind] [smallint] NULL,
[edu_input_indv_cd] [smallint] NULL,
[edu_1st_indv_cd] [smallint] NULL,
[edu_2nd_indv_cd] [smallint] NULL,
[mail_ord_buyer_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_ord_respndr_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_ord_donor_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[int_theatre_perf_arts_cd] [smallint] NULL,
[int_arts_cd] [smallint] NULL,
[int_travel_domestic_cd] [smallint] NULL,
[int_home_stereo_cd] [smallint] NULL,
[int_music_player_cd] [smallint] NULL,
[int_music_avid_lstnr_cd] [smallint] NULL,
[int_music_clctr_cd] [smallint] NULL,
[int_movie_clctr_cd] [smallint] NULL,
[int_auto_motor_racing_cd] [smallint] NULL,
[int_spectator_sport_footb_cd] [smallint] NULL,
[int_spectator_sport_baseb_cd] [smallint] NULL,
[int_spectator_sport_bsktb_cd] [smallint] NULL,
[int_spectator_sport_hockey_cd] [smallint] NULL,
[int_spectator_sport_soccer_cd] [smallint] NULL,
[int_spectator_sport_tennis_cd] [smallint] NULL,
[int_swpstake_contest_cd] [smallint] NULL,
[int_sports_grp_cd] [smallint] NULL,
[int_music_grp_cd] [smallint] NULL,
[int_nascar_cd] [smallint] NULL,
[int_upscale_living_cd] [smallint] NULL,
[int_cultural_living_cd] [smallint] NULL,
[veh_truck_owner_cd] [smallint] NULL,
[veh_mtrcyc_owner_cd] [smallint] NULL,
[veh_rv_owner_cd] [smallint] NULL,
[veh_known_owned_cd] [smallint] NULL,
[veh_dominant_lifestyle_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[psx_classic_clus_cd] [smallint] NULL,
[psx_group_id] [smallint] NULL,
[psx_classic_prec_lvl_cd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_avg_hh_income] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_median_hh_income] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_disposable_inc] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_discretionary_inc] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_tot_spend] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_ent] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_ent_movie] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_ent_livesports] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_ent_livearts] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_ent_museum] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_ent_cablesat] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_equip_sport] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_equip_toy] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_equip_videogame] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_equip_artist] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_equip_computer] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_photography] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_rec_vehicle] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ca_hs_rec_home_ent] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prizm_id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prizm_nm] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prizmsg_cd] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prizmsg_nm] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prizmls_cd] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prizmls_nm] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[msa_cma_nm] [varchar] (189) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dist_to_client_ven_mi] [smallint] NULL,
[dist_to_client_ven_km] [smallint] NULL,
[brkr_ind] [smallint] NULL,
[e3_sale_dt_max] [datetime] NULL,
[e3_event_dt_max] [datetime] NULL,
[e3_events_cnt] [smallint] NULL,
[e3_tkt_qty_avg] [real] NULL,
[e3_spend_total] [real] NULL,
[e3_spend_per_event] [real] NULL,
[e3_tkt_price_avg] [real] NULL,
[e3_tkt_price_min] [real] NULL,
[e3_tkt_price_max] [real] NULL,
[e3_txpr_pctile] [real] NULL,
[e3_tran_platinum_ind] [smallint] NULL,
[e3_tran_type_primary_ind] [smallint] NULL,
[e3_tran_type_resale_ind] [smallint] NULL,
[e3_ancil_parking_ind] [smallint] NULL,
[e3_ancil_upsell_ind] [smallint] NULL,
[grp_buyer_ind] [smallint] NULL,
[e3_dist_to_ven] [smallint] NULL,
[e3_dist_to_ven_local] [smallint] NULL,
[e3_dist_201_plus_miles_ind] [smallint] NULL,
[e3_spend_pe_m_concerts] [real] NULL,
[e3_spend_pe_m_arts] [real] NULL,
[e3_spend_pe_m_sports] [real] NULL,
[e3_spend_pe_m_family] [real] NULL,
[e3_spend_pe_m_misc] [real] NULL,
[e3_sow_m_concerts] [real] NULL,
[e3_sow_m_arts] [real] NULL,
[e3_sow_m_sports] [real] NULL,
[e3_sow_m_family] [real] NULL,
[e3_sow_m_misc] [real] NULL,
[e3_pref_tkt_qty_01_02] [real] NULL,
[e3_pref_tkt_qty_03_04] [real] NULL,
[e3_pref_tkt_qty_05_08] [real] NULL,
[e3_pref_tkt_qty_09_plus] [real] NULL,
[e3_pref_txpr_001_025] [real] NULL,
[e3_pref_txpr_026_050] [real] NULL,
[e3_pref_txpr_051_100] [real] NULL,
[e3_pref_txpr_101_200] [real] NULL,
[e3_pref_txpr_201_plus] [real] NULL,
[e3_pref_txpr_pctile_00_25] [real] NULL,
[e3_pref_txpr_pctile_25_49] [real] NULL,
[e3_pref_txpr_pctile_50_74] [real] NULL,
[e3_pref_txpr_pctile_75_89] [real] NULL,
[e3_pref_txpr_pctile_90_100] [real] NULL,
[e3_pref_purch_pd_presale] [real] NULL,
[e3_pref_purch_pd_onsale] [real] NULL,
[e3_pref_purch_pd_firstweek] [real] NULL,
[e3_pref_purch_pd_inbetween] [real] NULL,
[e3_pref_purch_pd_finalweek] [real] NULL,
[e3_pref_channel_internet] [real] NULL,
[e3_pref_channel_phone] [real] NULL,
[e3_pref_channel_mobile] [real] NULL,
[e3_pref_channel_box] [real] NULL,
[e3_pref_channel_outlet] [real] NULL,
[rfm_score] [smallint] NULL,
[rfm_grade] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[propn_score_minor_101] [smallint] NULL,
[propn_score_minor_102] [smallint] NULL,
[propn_score_minor_103] [smallint] NULL,
[propn_score_minor_104] [smallint] NULL,
[propn_score_minor_105] [smallint] NULL,
[propn_score_minor_106] [smallint] NULL,
[propn_score_minor_107] [smallint] NULL,
[propn_score_minor_108] [smallint] NULL,
[propn_score_minor_109] [smallint] NULL,
[propn_score_minor_110] [smallint] NULL,
[propn_score_minor_111] [smallint] NULL,
[propn_score_minor_199] [smallint] NULL,
[propn_score_minor_201] [smallint] NULL,
[propn_score_minor_202] [smallint] NULL,
[propn_score_minor_203] [smallint] NULL,
[propn_score_minor_204] [smallint] NULL,
[propn_score_minor_205] [smallint] NULL,
[propn_score_minor_206] [smallint] NULL,
[propn_score_minor_207] [smallint] NULL,
[propn_score_minor_299] [smallint] NULL,
[propn_score_minor_301] [smallint] NULL,
[propn_score_minor_302] [smallint] NULL,
[propn_score_minor_399] [smallint] NULL,
[propn_score_minor_401] [smallint] NULL,
[propn_score_minor_402] [smallint] NULL,
[propn_score_minor_403] [smallint] NULL,
[propn_score_minor_410] [smallint] NULL,
[propn_score_minor_412] [smallint] NULL,
[propn_score_minor_420] [smallint] NULL,
[propn_score_minor_423] [smallint] NULL,
[propn_score_minor_430] [smallint] NULL,
[propn_score_minor_432] [smallint] NULL,
[propn_score_minor_440] [smallint] NULL,
[propn_score_minor_442] [smallint] NULL,
[propn_score_minor_450] [smallint] NULL,
[propn_score_minor_460] [smallint] NULL,
[propn_score_minor_470] [smallint] NULL,
[propn_score_minor_480] [smallint] NULL,
[propn_score_minor_491] [smallint] NULL,
[propn_score_minor_499] [smallint] NULL,
[client_event_cnt] [smallint] NULL,
[client_tkt] [smallint] NULL,
[client_sp] [real] NULL,
[client_sale_dt_min] [datetime] NULL,
[client_sale_dt_max] [datetime] NULL,
[client_pe_tkt_cnt] [real] NULL,
[client_pe_sp] [real] NULL,
[client_tkt_price] [real] NULL,
[client_tkt_price_max] [real] NULL,
[client_tkt_price_min] [real] NULL,
[client_walkup_buyer_ind] [smallint] NULL
)
GO
