CREATE TABLE [ods].[SurveyGizmo_surveyResponse]
(
[SK] [int] NOT NULL,
[Response_id] [int] NOT NULL,
[Response_contact_id] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_status] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_is_test_data] [bit] NULL,
[Response_date_submitted] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_session_id] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_language] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_date_started] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_link_id] [int] NULL,
[Response_ip_address] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_referer] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_user_agent] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_response_time] [int] NULL,
[Response_longitude] [decimal] (20, 17) NULL,
[Response_latitude] [decimal] (20, 17) NULL,
[Response_country] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_city] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_region] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_postal] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_dma] [int] NULL,
[Response_url_variables_controller] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_controller_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_controller_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_controller_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_action_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_action_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_action_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_id_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_id_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_id_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_module_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_module_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_module_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sgtarget_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sgtarget_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sgtarget_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_slanguage_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_slanguage_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_slanguage_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_build_test_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_build_test_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_build_test_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_collab_test_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_collab_test_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_collab_test_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_tester_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_tester_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_tester_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_tester_name_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_tester_name_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_tester_name_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_tester_id_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_tester_id_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_tester_id_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_link_id_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_link_id_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_link_id_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_skip_actions_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_skip_actions_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sg_skip_actions_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_?preview_frame_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_?preview_frame_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables_?preview_frame_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sgapptest_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sgapptest_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___sgapptest_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___ref_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___ref_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___ref_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___passthrough_key] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___passthrough_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_url_variables___passthrough_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_id] [int] NULL,
[Response_survey_data_type] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_question] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_section_id] [int] NULL,
[Response_survey_data_shown] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_options_] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_options_id] [int] NULL,
[Response_survey_data_options_option] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_options_answer] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_options_card_id] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_options_card_answer] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_options_set_id] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_options_set_answer] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_options_choice_id] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response_survey_data_options_choice_answer] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_CreatedOn] [datetime] NOT NULL CONSTRAINT [DF__SurveyGiz__ETL_C__71280E65] DEFAULT ([etl].[ConvertToLocalTime](CONVERT([datetime2](0),getdate(),(0)))),
[ETL_CreatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__SurveyGiz__ETL_C__721C329E] DEFAULT (suser_sname()),
[ETL_UpdatedOn] [datetime] NOT NULL CONSTRAINT [DF__SurveyGiz__ETL_U__731056D7] DEFAULT ([etl].[ConvertToLocalTime](CONVERT([datetime2](0),getdate(),(0)))),
[ETL_UpdatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__SurveyGiz__ETL_U__74047B10] DEFAULT (suser_sname())
)
GO
ALTER TABLE [ods].[SurveyGizmo_surveyResponse] ADD CONSTRAINT [PK__SurveyGi__E966613C40D9BC89] PRIMARY KEY CLUSTERED  ([SK], [Response_id])
GO
