CREATE TABLE [ods].[SurveyGizmo_surveyQuestion]
(
[SK] [int] NOT NULL,
[Question_id] [int] NOT NULL,
[Question_base_type] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_type] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_shortname] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_has_showhide_deps] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_comment] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_title_English] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_hidden] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_map_key] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_show_title] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_question_description_above] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_soft_required] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_required] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_disabled] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_labels_right] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_option_sort] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_hide_after_response] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_custom_css] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_break_after] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_url] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_orientation] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_question_description_English] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_options_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_options_value] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_options_properties] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_messages_conjoint_best_label_English] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_properties_messages_conjoint_worst_label_English] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_options_title_English] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_options_properties_disabled] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_options_properties_options_] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_options_properties_options_label] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_options_properties_options_labelvalue] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_options_properties_options_resource] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Question_options_properties_options_uniqid] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_CreatedOn] [datetime] NOT NULL CONSTRAINT [DF__SurveyGiz__ETL_C__7E820983] DEFAULT ([etl].[ConvertToLocalTime](CONVERT([datetime2](0),getdate(),(0)))),
[ETL_CreatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__SurveyGiz__ETL_C__7F762DBC] DEFAULT (suser_sname()),
[ETL_UpdatedOn] [datetime] NOT NULL CONSTRAINT [DF__SurveyGiz__ETL_U__006A51F5] DEFAULT ([etl].[ConvertToLocalTime](CONVERT([datetime2](0),getdate(),(0)))),
[ETL_UpdatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__SurveyGiz__ETL_U__015E762E] DEFAULT (suser_sname())
)
GO
ALTER TABLE [ods].[SurveyGizmo_surveyQuestion] ADD CONSTRAINT [PK__SurveyGi__32151C615E9236F1] PRIMARY KEY CLUSTERED  ([SK])
GO
