CREATE TABLE [stg].[Infogroup_Appends]
(
[xFEFF SSB CRMSYSTEM CONTACT ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystem] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address Line1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address Line2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneDay] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneEve] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Match Pass] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Consumer Match Pass] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sequence Number] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 ADDRESS SOURCE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 ADDRESS STATUS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 PANDER CODE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 LOCAL ADDRESS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 UNIT INFORMATION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 SECONDARY ADDRESS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 LONG CITY NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 SHORT CITY NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 STATE ABBREVIATION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 ZIP CODE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 ZIP4 CODE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 RESERVED 1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 MAILABILITY SCORE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 RESERVED 2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 MILITARY ZIP CODE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 OPAC INDICATOR] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 NDI AFFIRMED APT] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 SECONDARY INDICATOR] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 STATE CODE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 COUNTY CODE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 LONG CITY INDICATOR] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 CARRIER ROUTE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 LOT NUMBER] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 LOT SORTATION NUMBER] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 PRESTIGE CITY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AH1 DELIVERY POINT] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Match Level] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Match Score] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABI Number] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Record Type Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Household ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Selected Individual ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Contact_Manager] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Company_Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Primary_Address] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Primary_City_Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Primary_State_Abbreviation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Primary_ZIP_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Primary_ZIP4_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Primary_ZIP_Code_Plus_4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Primary_Carrier_Route_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Primary_State_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_County_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_County_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_MSA_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_MSA_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_CBSA_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_CBSA_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Metro_Micro_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_CSA_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_CSA_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Census_Tract] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Block_Group] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_FILLER_SIZE_11] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_FILLER_SIZE_10] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Geo_Match_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_Address] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_City_Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_State_Abbreviation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_State_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_ZIP_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_ZIP4_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_ZIP_Plus_Four_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_Carrier_Route_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Telephone_NumberF1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Fax_NumberF1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Toll_Free_NumberF1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Web_Address_URL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Selected_SIC_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Selected_SIC_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Code1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Description1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Code2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Description2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Code3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Description3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Code4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Description4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Code5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Description5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Code6] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Franchise_Specialty_Description6] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_True_Franchise_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Industry_Specific_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Industry_Specific_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Primary_SIC_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Primary_SIC_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_SIC_Code_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_SIC_Description_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_SIC_Code_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_SIC_Description_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_SIC_Code_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_SIC_Description_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_SIC_Code_4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Secondary_SIC_Description_4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_NAICS_Code8] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_NAICS_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Location_Employment_Size_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Location_Employment_Size_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Actual_Location_Employment_Size5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Corporate_Employment_Size_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Corporate_Employment_Size_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Actual_Corporate_Employment_Size] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Modeled_Employment_Size_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Location_Sales_Volume_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Location_Sales_Volume_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Actual_Location_Sales_Volume] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Corporate_Sales_Volume_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Corporate_Sales_Volume_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Actual_Corporate_Sales_Volume] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Asset_Size_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Contact_Last_Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Contact_First_Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Contact_Salutation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Contact_Gender_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Contact_Professional_Title_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Contact_Title_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Contact_Title_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Filler_Ethnicity_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Filler_Ethnicity_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Key_Code20] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Title_Address] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_ABI_Number] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_infoUSA_Subsidiary_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_infoUSA_Parent_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Site_Number] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Business_Status_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Business_Status_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Public_Private_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Stock_Exchange_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Stock_Exchange_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Ticker_Symbol] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Public_Filing_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Fortune_Magazine_Ranking] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Individual_Firm_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Individual_Firm_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Year_SIC_Added_to_Record] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Year_First_Appeared_in_Yellow_Pages] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Year_Established] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Yellow_Page_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Transaction_Date] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Transaction_Type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Tele_Research_Date] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Call_Status_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Call_Status_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Business_Credit_Score_Code2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Business_Credit_Score_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Business_Credit_Score] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Ad_Size_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Ad_Size_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Office_Size_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Office_Size_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Population_Size_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Population_Size_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Work_At_Home_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Own_Lease_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Square_Footage8] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Square_Footage_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Radial_Distance_From_Target_Element] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Actual_Num_Bus_at_Multi_Tenant_Location] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Multi_Tenant_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Multi_Tenant_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Building_Number_of_Multi_Tenant_Location] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Number_of_Personal_Computers_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Number_of_Personal_Computers_Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Affluent_Neighborhood_Location_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Big_Business_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Female_Business_Exec_Owner_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Growing_Shrinking_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_High_Income_Executive_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_High_Tech_Business_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Medium_Business_Entrepreneur_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Small_Business_Entrepreneur_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Delivery_Point_Bar_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Presort_Endorsement_Line] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Presort_Bag_Number] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Presort_Bundle_Number] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Presort_Line_of_Travel] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Tertiary_Address] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Tertiary_City_Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Tertiary_State_Abbreviation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Tertiary_ZIP_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Tertiary_ZIP4_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Tertiary_ZIP_Plus_Four_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Tertiary_Carrier_Route_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_White_Collar_Percentage_Formatted] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_White_Collar_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Production_Date] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Presort_Sequence_Number] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Obsolescence_Date] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Production_Date_Formatted] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Source] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Book_Number] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Government_Segment_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Foreign_Parent_Indicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_Import_Export_Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BE_1849_Record_Marker] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
